# Programming Assignment: First Data Interaction

Welcome to the assignment for First Data Interaction.

In the previous notebook you got familiar with datasets loading methods, such as: CSV, JSON, SQL and so on. After loading them using `pandas` functions, you obtained `pd.Series` and `pd.DataFrame` instances. These instances have several useful methods that help with initial data exploration and interaction. This helps with understanding of what data is contained inside these data structures, their types, as well as important statistics/information, such as: standard deviation, variance, unique values, number of null values etc.

Besides these statistics and information, datasets loaded in `pandas` data structure offer the possibility to efficiently select subsets of data, grouping them by certain criterion and aggregate data according with either built-in or custom functions.

In this assignment, you'll understand and apply basic dataset exploration techniques using built-in `pandas` DataFrame and Series methods for initial data exploration and interaction.

**What You will do in this Assignment**

* Explore a numeric `pd.Series` using various pandas methods: `.head()`, `.tail()`, `.dtype`, `.isna()`, `.mean()`, `.median()`, `.min()`, `.max()`, `.std()`, `.var()`, and `.describe()`.
* Explore a `pd.DataFrame` using structural and statistical methods: `.head()`, `.tail()`, `.shape`, `.columns`, `.dtypes`, `.isna()`, `.describe()`, and `.memory_usage()`.
* Select specific subsets of data using single and multi-column selection, positional indexing with `.iloc[]`, label-based indexing with `.loc[]`, and boolean filtering.
* Group data by categorical columns and apply aggregation functions using `.groupby()`, `.size()`, and `.agg()`.

Let's get started!

---
<a name='submission'></a>

<h4 style="color:green; font-weight:bold;">TIPS FOR SUCCESSFUL GRADING OF YOUR ASSIGNMENT:</h4>

* All cells are frozen except for the ones where you need to submit your solutions or when explicitly mentioned you can interact with it.

* In each exercise cell, look for comments `### START CODE HERE ###` and `### END CODE HERE ###`. These show you where to write the solution code. **Do not add or change any code that is outside these comments**.

* You can add new cells to experiment but these will be omitted by the grader, so don't rely on newly created cells to host your solution code, use the provided places for this.

---

## Table of Contents
- [Imports](#imports)
- [Prerequisites](#prerequisites)
- [1 - `pd.Series` Initial Exploration](#1---series-exploration)
    - [1.1 - Inspecting Variables](#11---inspect-series)
    - [1.2 - Checking Data Types](#12---dtypes-series)
    - [1.3 - Identifying Missing Values](#13---missing-series)
    - [1.4 - Numerical Statistics](#14---numeric-stats-series)
    - [1.5 - Frequency-Based Statistics](#15---freq-stats-series)
    - [1.6 - Memory Usage](#16---memory-series)
    - **[Exercise 1 - `explore_numeric_series`](#exercise-1---explore-numeric-series)**
- [2 - `pd.DataFrame` Initial Exploration](#2---dataframe-exploration)
    - [2.1 - Inspecting the DataFrame](#21---inspect-df)
    - [2.2 - Shape and Structure](#22---shape-df)
    - [2.3 - Identifying Missing Values](#23---missing-df)
    - [2.4 - Numerical Statistics](#24---numeric-stats-df)
    - [2.5 - Frequency-Based Statistics](#25---freq-stats-df)
    - [2.6 - Memory Usage](#26---memory-df)
    - **[Exercise 2 - `explore_pandas_dataframe`](#exercise-2---explore-pandas-dataframe)**
- [3 - Data Selection](#3---data-selection)
    - [3.1 - Column Selection](#31---column-selection)
    - [3.2 - Positional Selection with `.iloc[]`](#32---iloc-selection)
    - [3.3 - Label-Based Selection with `.loc[]`](#33---loc-selection)
    - [3.4 - Boolean Filtering](#34---boolean-filtering)
    - **[Exercise 3 - `select_from_dataframe`](#exercise-3---select-from-dataframe)**
- [4 - GroupBy and Aggregation](#4---groupby-aggregation)
    - [4.1 - Grouping with `.groupby()`](#41---groupby)
    - [4.2 - Counting Group Sizes](#42---group-sizes)
    - [4.3 - Multiple Aggregations with `.agg()`](#43---agg)
    - **[Exercise 4 - `groupby_and_aggregate`](#exercise-4---groupby-and-aggregate)**

<a name='imports'></a>
## Imports

In [195]:
import numpy as np
import pandas as pd

In [196]:
import helper_utils
import unittests

<a name='prerequisites'></a>
## Prerequisites

This notebook uses the **Iris dataset**, similar to the one that was downloaded in **Notebook 1**. The `helper_utils` module provided with this notebook will automatically download the dataset, but you will be required to use previously obtained knowledge to load this dataset. You will be provided with the `Path` object to this dataset and the name of the JSON file, as well as the type of the structure that was used for this dataset (contents of the file structure).

<p style="color:red; font-weight:bold;">NOTE: Take into consideration that this Notebook is developed keeping in mind that default dataset (Iris Dataset) is used. No automatic evaluation will be done in case you use other datasets than the one that are automatically downloaded.</p>

* `.json` - JSON dataset - Iris Dataset - [AVAILABLE HERE](https://www.kaggle.com/datasets/rtatman/iris-dataset-json-version)

In [197]:
# Create datasets folder/directory to store JSON Iris Dataset
helper_utils.make_data_dir()

JSON file datasets located at: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1\notebooks\notebook_2_first_data_interaction\datasets\json

In [198]:
# Load the Iris dataset
helper_utils.download_json_dataset()

<a name='1---series-exploration'></a>
## 1 - `pd.Series` Initial Exploration

Since a `pd.Series` represents a single variable, exploration focuses on understanding its values, data type, missing data and basic statistics. The subsections below cover the most commonly used exploration methods.

The `sepalLength` column from the Iris dataset is used as the running example throughout this section.

<a name='11---inspect-series'></a>
### 1.1 Inspecting Variables

The most basic inspection is looking at the first or last few elements of the Series using `.head()` and `.tail()`:

In [199]:
sample_predef_df = helper_utils.get_sample_dataframe()
sample_predef_df

     sepalLength  sepalWidth  petalLength  petalWidth     species
0            6.1         2.8          4.7         1.2  versicolor
1            5.7         3.8          1.7         0.3      setosa
2            7.7         2.6          6.9         2.3   virginica
3            6.0         2.9          4.5         1.5  versicolor
4            6.8         2.8          4.8         1.4  versicolor
..           ...         ...          ...         ...         ...
145          6.1         2.8          4.0         1.3  versicolor
146          4.9         2.5          4.5         1.7   virginica
147          5.8         4.0          1.2         0.2      setosa
148          5.8         2.6          4.0         1.2  versicolor
149          7.1         3.0          5.9         2.1   virginica

[150 rows x 5 columns]

In [200]:
# Use sepalLength column as a sample Series
sepal_length: pd.Series = sample_predef_df["sepalLength"]
sepal_length

0      6.1
1      5.7
2      7.7
3      6.0
4      6.8
      ...
145    6.1
146    4.9
147    5.8
148    5.8
149    7.1
Name: sepalLength, Length: 150, dtype: float64

In [201]:
# First 5 rows - .head()
print("First 5 rows (.head(5)):")
print(sepal_length.head(5))

First 5 rows (.head(5)):
0    6.1
1    5.7
2    7.7
3    6.0
4    6.8
Name: sepalLength, dtype: float64

In [202]:
# Last 3 rows - .tail()
print("Last 3 rows (.tail(3)):")
print(sepal_length.tail(3))

Last 3 rows (.tail(3)):
147    5.8
148    5.8
149    7.1
Name: sepalLength, dtype: float64

<a name='12---dtypes-series'></a>
### 1.2 Checking Data Types

To understand what kind of data is stored in a Series, use the `.dtype` attribute:

In [203]:
# Numeric Series
numeric_series: pd.Series = pd.Series([1, 2, 3, 4], name="NUMBERS")
numeric_series

0    1
1    2
2    3
3    4
Name: NUMBERS, dtype: int64

In [204]:
# Numeric series data type
print(f"Numeric dtype: {numeric_series.dtype}")

Numeric dtype: int64

In [205]:
# String Series
string_series: pd.Series = pd.Series(["cat", "dog", "fish"], name="ANIMALS")
string_series

0     cat
1     dog
2    fish
Name: ANIMALS, dtype: str

In [206]:
# String series data type
print(f"String dtype: {string_series.dtype}")

String dtype: str

In [207]:
# Float Series from the Iris dataset
print(f"sepalLength dtype: {sepal_length.dtype}")

sepalLength dtype: float64

<a name='13---missing-series'></a>
### 1.3 Identifying Missing Values

Missing values (represented as `NaN` or `None`) are very common in real-world datasets. `pandas` provides `.isna()` to detect them:

In [208]:
# Series with missing values
series_with_nulls: pd.Series = pd.Series(
    data=[1, np.nan, 3, None, 5, np.nan],
    name="WITH_MISSING"
)
series_with_nulls

0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    NaN
Name: WITH_MISSING, dtype: float64

In [209]:
# Boolean mask: True where value is missing
print("Boolean mask (.isna()):")
print(series_with_nulls.isna())

Boolean mask (.isna()):
0    False
1     True
2    False
3     True
4    False
5     True
Name: WITH_MISSING, dtype: bool

In [210]:
# Total count of missing values
print(f"Total missing values (.isna().sum()): {series_with_nulls.isna().sum()}")

Total missing values (.isna().sum()): 3

In [211]:
# Proportion of missing values
print(f"Proportion missing (.isna().mean()): {series_with_nulls.isna().mean()}")

Proportion missing (.isna().mean()): 0.5

<a name='14---numeric-stats-series'></a>
### 1.4 Numerical Statistics

For numeric Series, `pandas` exposes a rich set of aggregation methods. They all ignore `NaN` values by default:

In [212]:
# Numeric Series
numeric_series: pd.Series = pd.Series(
    data=[10, 10, 10, 20, 30, 100, 0, -100, -20, 20, 10, 45, 20, 30, 40, 50],
    name="NUMERIC_STATS"
)
numeric_series

0      10
1      10
2      10
3      20
4      30
5     100
6       0
7    -100
8     -20
9      20
10     10
11     45
12     20
13     30
14     40
15     50
Name: NUMERIC_STATS, dtype: int64

In [213]:
# Individual Statistics
print(f"Mean (.mean()): {numeric_series.mean()}")
print(f"Median (.median()): {numeric_series.median()}")
print(f"Min (.min()): {numeric_series.min()}")
print(f"Max (.max()): {numeric_series.max()}")
print(f"Std (.std()): {numeric_series.std()}")
print(f"Var (.var()): {numeric_series.var()}")

Mean (.mean()): 17.1875
Median (.median()): 20.0
Min (.min()): -100
Max (.max()): 100
Std (.std()): 40.98653234092064
Var (.var()): 1679.8958333333333

In [214]:
# Compact summary via .describe()
print("Summary statistics (.describe()):")
print(numeric_series.describe())

Summary statistics (.describe()):
count     16.000000
mean      17.187500
std       40.986532
min     -100.000000
25%       10.000000
50%       20.000000
75%       32.500000
max      100.000000
Name: NUMERIC_STATS, dtype: float64

<a name='15---freq-stats-series'></a>
### 1.5 Frequency-Based Statistics (Categorical)

For categorical (non-numeric) Series, frequency-based methods reveal how often each unique value appears:

In [215]:
# Use the species column from Iris as a categorical example
species_series: pd.Series = sample_predef_df["species"]
species_series

0      versicolor
1          setosa
2       virginica
3      versicolor
4      versicolor
          ...
145    versicolor
146     virginica
147        setosa
148    versicolor
149     virginica
Name: species, Length: 150, dtype: str

In [216]:
# Frequency of each unique value
print("Frequency of unique values (.value_counts()):")
print(species_series.value_counts())

Frequency of unique values (.value_counts()):
species
versicolor    50
setosa        50
virginica     50
Name: count, dtype: int64

In [217]:
# Most frequent value(s)
print(f"Most frequent value (.mode()): {species_series.mode().tolist()}")

Most frequent value (.mode()): ['setosa', 'versicolor', 'virginica']

In [218]:
# Number of unique values
print(f"Unique value count (.nunique()): {species_series.nunique()}")

Unique value count (.nunique()): 3

In [219]:
# Describe a categorical Series
print("Summary statistics (.describe()):")
print(species_series.describe())

Summary statistics (.describe()):
count            150
unique             3
top       versicolor
freq              50
Name: species, dtype: object

<a name='16---memory-series'></a>
### 1.6 Memory Usage

Understanding how much memory a `pd.Series` consumes is important when working with large datasets:

In [220]:
# Memory without object sizes
print(f"Memory (.memory_usage()): {sepal_length.memory_usage()} bytes")

Memory (.memory_usage()): 1332 bytes

In [221]:
# Mixed pd.Series with multiple values of different data types
mixed_series: pd.Series = pd.Series(
    data=[10, "CANADA", 30, np.nan, "USA"],
    name="MIXED"
)
mixed_series

0        10
1    CANADA
2        30
3       NaN
4       USA
Name: MIXED, dtype: object

In [222]:
# Memory with deep inspection of object types (recommended for object dtype)
print(f"Memory deep (.memory_usage(deep=True)): {mixed_series.memory_usage(deep=True)} bytes")

Memory deep (.memory_usage(deep=True)): 343 bytes

<a name='exercise-1---explore-numeric-series'></a>
### **Exercise 1 - `explore_numeric_series`**

**Your Task:**

Implement the `explore_numeric_series` function. A numeric `pd.Series` named `"TEMPERATURE_DATA"` is predefined inside the function body - **do not modify it**. Your task is to apply the correct `pandas` methods and return the results as a tuple.

The function must return a tuple of **11** elements in exactly this order:

1. `head_5` (`pd.Series`): First **5** rows.
2. `tail_3` (`pd.Series`): Last **3** rows.
3. `dtype_result`: Data type of the Series values.
4. `null_count` (`int`): Total count of `NaN`/`None` values.
5. `mean_val` (`float`): Arithmetic mean.
6. `median_val` (`float`): Median value.
7. `min_val` (`float`): Minimum value.
8. `max_val` (`float`): Maximum value.
9. `std_val` (`float`): Standard deviation.
10. `var_val` (`float`): Variance.
11. `describe_result` (`pd.Series`): Summary statistics.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
  **For `head_5`:** Use the `pd.Series` method that returns the first `n` rows, passing the desired number of rows as an argument.

  **For `tail_3`:** Use the `pd.Series` method that returns the last `n` rows, passing the desired number of rows as an argument.

  **For `dtype_result`:** Use the `pd.Series` attribute (not a method — no parentheses needed) that returns the data type of the Series values.

  **For `null_count`:** Recall that null detection in `pandas` can be done with a method that returns a boolean `pd.Series`, and then another method can aggregate those booleans into a single total count.

  **For `mean_val`:** Use the `pd.Series` method that computes the arithmetic average of all non-null values.

  **For `median_val`:** Use the `pd.Series` method that returns the middle value when all values are sorted.

  **For `min_val`:** Use the `pd.Series` method that returns the smallest value in the Series.

  **For `max_val`:** Use the `pd.Series` method that returns the largest value in the Series.

  **For `std_val`:** Use the `pd.Series` method that measures how spread out values are around the mean (square root of variance).

  **For `var_val`:** Use the `pd.Series` method that measures the average squared deviation from the mean.

  **For `describe_result`:** Use the `pd.Series` method that computes a summary of key statistics (count, mean, std, min, quartiles, max) all at once.

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>

  **For `head_5`:** Use the following code:
  ```py
  head_5 = s.head(5)
  ```

  **For `tail_3`:** Use the following code:
  ```py
  tail_3 = s.tail(3)
  ```

  **For `dtype_result`:** Use the following code:
  ```py
  dtype_result = s.dtype
  ```

  **For `null_count`:** Use the following code:
  ```py
  null_count = s.isna().sum()
  ```

  **For `mean_val`:** Use the following code:
  ```py
  mean_val = s.mean()
  ```

  **For `median_val`:** Use the following code:
  ```py
  median_val = s.median()
  ```

  **For `min_val`:** Use the following code:
  ```py
  min_val = s.min()
  ```

  **For `max_val`:** Use the following code:
  ```py
  max_val = s.max()
  ```

  **For `std_val`:** Use the following code:
  ```py
  std_val = s.std()
  ```

  **For `var_val`:** Use the following code:
  ```py
  var_val = s.var()
  ```

  **For `describe_result`:** Use the following code:
  ```py
  describe_result = s.describe()
  ```

  </details>

</details>

In [223]:
# GRADED FUNCTION: explore_numeric_series
def explore_numeric_series() -> tuple:
    """Explores a predefined numeric pd.Series using various pandas methods.

    Returns:
        tuple: A tuple of 11 elements:
            - head_5 (pd.Series): First 5 values of the Series.
            - tail_3 (pd.Series): Last 3 values of the Series.
            - dtype_result: Data type of the Series values.
            - null_count (int): Total count of null/NaN values.
            - mean_val (float): Arithmetic mean.
            - median_val (float): Median value.
            - min_val (float): Minimum value.
            - max_val (float): Maximum value.
            - std_val (float): Standard deviation.
            - var_val (float): Variance.
            - describe_result (pd.Series): Summary statistics.
    """
    # Predefined data - do not modify this block
    data = [22.5, 27.2, 31.8, None, 28.6, 29.0, None, 32.1, 35.0, 24.1, 30.5, 26.7, 28.9, None, 33.2]
    series = pd.Series(data=data, name="TEMPERATURE_DATA")

    ### START CODE HERE ###

    head_5 = series.head(5)
    tail_3 = series.tail(3)
    dtype_result = series.dtype
    null_count = series.isna().sum()
    mean_val = series.mean()
    median_val = series.median()
    min_val = series.min()
    max_val = series.max()
    std_val = series.std()
    var_val = series.var()
    describe_result = series.describe()

    ### END CODE HERE ###

    return (head_5, tail_3, dtype_result, null_count, mean_val, median_val, min_val, max_val, std_val, var_val, describe_result)

In [224]:
head_5, tail_3, dtype_result, null_count, mean_val, median_val, min_val, max_val, std_val, var_val, describe_result = explore_numeric_series()

In [225]:
# First 5 rows
head_5

0    22.5
1    27.2
2    31.8
3     NaN
4    28.6
Name: TEMPERATURE_DATA, dtype: float64

In [226]:
# Last 3 rows
tail_3

12    28.9
13     NaN
14    33.2
Name: TEMPERATURE_DATA, dtype: float64

In [227]:
# Data type and null count
print(f"dtype: {dtype_result}")
print(f"nulls: {null_count}")

dtype: float64
nulls: 3

In [228]:
# Numerical statistics
print(f"Mean (mean): {mean_val}")
print(f"Median (median): {median_val}")
print(f"Minimum Value (min): {min_val}")
print(f"Maximum Value (max): {max_val}")
print(f"Standard Deviation (std): {std_val}")
print(f"Variance (var): {var_val}")

Mean (mean): 29.133333333333326
Median (median): 28.95
Minimum Value (min): 22.5
Maximum Value (max): 35.0
Standard Deviation (std): 3.669117638128307
Variance (var): 13.462424242424246

In [229]:
# Summary statistics
describe_result

count    12.000000
mean     29.133333
std       3.669118
min      22.500000
25%      27.075000
50%      28.950000
75%      31.875000
max      35.000000
Name: TEMPERATURE_DATA, dtype: float64

In [230]:
# Test your implementation
unittests.exercise_1(explore_numeric_series)

 All tests passed!

<a name='2---dataframe-exploration'></a>
## 2 - `pd.DataFrame` Initial Exploration

Since a `pd.DataFrame` is a two-dimensional structure, its exploration involves understanding not only the values but also the shape, column types, missing data patterns, and summary statistics across multiple variables simultaneously.

<a name='21---inspect-df'></a>
### 2.1 Inspecting the DataFrame

Use `.head()` - for first rows and `.tail()` - for last rows, to quickly preview the data:

In [231]:
# Sample DataFrame for demonstration
demo_df: pd.DataFrame = pd.DataFrame({
    "name":       ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "age":        [25, 30, 35, 28, 22],
    "salary":     [50000.0, 60000.0, 70000.0, 55000.0, 48000.0],
    "department": ["HR", "Engineering", "Engineering", "Marketing", "HR"],
    "score":      [88, 95, np.nan, 76, None],
})
demo_df

      name  age   salary   department  score
0    Alice   25  50000.0           HR   88.0
1      Bob   30  60000.0  Engineering   95.0
2  Charlie   35  70000.0  Engineering    NaN
3    Diana   28  55000.0    Marketing   76.0
4      Eve   22  48000.0           HR    NaN

In [232]:
print("First 3 rows (.head(3)):")
demo_df.head(3)

First 3 rows (.head(3)):

      name  age   salary   department  score
0    Alice   25  50000.0           HR   88.0
1      Bob   30  60000.0  Engineering   95.0
2  Charlie   35  70000.0  Engineering    NaN

In [233]:
print("Last 2 rows (.tail(2)):")
demo_df.tail(2)

Last 2 rows (.tail(2)):

    name  age   salary department  score
3  Diana   28  55000.0  Marketing   76.0
4    Eve   22  48000.0         HR    NaN

<a name='22---shape-df'></a>
### 2.2 Shape and Structure

Key attributes and methods for understanding the structural layout of a DataFrame:

In [234]:
# Dimensions: (rows, columns)
print(f"Shape (.shape): {demo_df.shape}")

Shape (.shape): (5, 5)

In [235]:
# Column names
print(f"Columns (.columns): {demo_df.columns.tolist()}")

Columns (.columns): ['name', 'age', 'salary', 'department', 'score']

In [236]:
# Data type per column
print("Data types per column (.dtypes):")
print(demo_df.dtypes)

Data types per column (.dtypes):
name              str
age             int64
salary        float64
department        str
score         float64
dtype: object

In [237]:
# Concise structural summary
print("Structural summary (.info()):")
demo_df.info()

Structural summary (.info()):
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   age         5 non-null      int64
 2   salary      5 non-null      float64
 3   department  5 non-null      str
 4   score       3 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 332.0 bytes

<a name='23---missing-df'></a>
### 2.3 Identifying Missing Values

The same `.isna()` approach works on DataFrames - now operating across all columns simultaneously:

In [238]:
# Boolean mask per cell
print("Boolean mask (.isna()):")
print(demo_df.isna())

Boolean mask (.isna()):
    name    age  salary  department  score
0  False  False   False       False  False
1  False  False   False       False  False
2  False  False   False       False   True
3  False  False   False       False  False
4  False  False   False       False   True

In [239]:
# Count of missing values per column
print("Missing count per column (.isna().sum()):")
print(demo_df.isna().sum())

Missing count per column (.isna().sum()):
name          0
age           0
salary        0
department    0
score         2
dtype: int64

In [240]:
# Proportion of missing values per column
print("Missing proportion per column (.isna().mean()):")
print(demo_df.isna().mean())

Missing proportion per column (.isna().mean()):
name          0.0
age           0.0
salary        0.0
department    0.0
score         0.4
dtype: float64

<a name='24---numeric-stats-df'></a>
### 2.4 Numerical Statistics

Statistical methods on a DataFrame apply across all numeric columns simultaneously:

In [241]:
# Summary statistics across all numeric columns
print("Summary statistics (.describe()):")
print(demo_df.describe())

Summary statistics (.describe()):
             age        salary      score
count   5.000000      5.000000   3.000000
mean   28.000000  56600.000000  86.333333
std     4.949747   8820.430828   9.609024
min    22.000000  48000.000000  76.000000
25%    25.000000  50000.000000  82.000000
50%    28.000000  55000.000000  88.000000
75%    30.000000  60000.000000  91.500000
max    35.000000  70000.000000  95.000000

In [242]:
# Column-wise mean (numeric columns only)
numeric_cols = ["age", "salary", "score"]
print("Mean per numeric column (.mean()):")
print(demo_df[numeric_cols].mean())

Mean per numeric column (.mean()):
age          28.000000
salary    56600.000000
score        86.333333
dtype: float64

<a name='25---freq-stats-df'></a>
### 2.5 Frequency-Based Statistics

For categorical columns in a DataFrame, use `.value_counts()` on individual columns and `.nunique()` across all columns:

In [243]:
# Value counts for a single categorical column
print("Value counts for 'department' (.value_counts()):")
print(demo_df["department"].value_counts())

Value counts for 'department' (.value_counts()):
department
HR             2
Engineering    2
Marketing      1
Name: count, dtype: int64

In [244]:
# Number of unique values per column
print("Unique value count per column (.nunique()):")
print(demo_df.nunique())

Unique value count per column (.nunique()):
name          5
age           5
salary        5
department    3
score         3
dtype: int64

In [245]:
# Full describe including non-numeric columns
print("Full describe (.describe(include='all')):")
print(demo_df.describe(include="all"))

Full describe (.describe(include='all')):
         name        age        salary department      score
count       5   5.000000      5.000000          5   3.000000
unique      5        NaN           NaN          3        NaN
top     Alice        NaN           NaN         HR        NaN
freq        1        NaN           NaN          2        NaN
mean      NaN  28.000000  56600.000000        NaN  86.333333
std       NaN   4.949747   8820.430828        NaN   9.609024
min       NaN  22.000000  48000.000000        NaN  76.000000
25%       NaN  25.000000  50000.000000        NaN  82.000000
50%       NaN  28.000000  55000.000000        NaN  88.000000
75%       NaN  30.000000  60000.000000        NaN  91.500000
max       NaN  35.000000  70000.000000        NaN  95.000000

<a name='26---memory-df'></a>
### 2.6 Memory Usage

`.memory_usage(deep=True)` reports the memory consumption per column in bytes:

In [246]:
# Memory per column
print("Memory per column (.memory_usage(deep=True)):")
print(demo_df.memory_usage(deep=True))

Memory per column (.memory_usage(deep=True)):
Index         132
name          268
age            40
salary         40
department    280
score          40
dtype: int64

In [247]:
# Total memory across all columns
print(f"Total memory: {demo_df.memory_usage(deep=True).sum()} bytes")

Total memory: 800 bytes

<a name='exercise-2---explore-pandas-dataframe'></a>
### **Exercise 2 - `explore_pandas_dataframe`**

**Your Task:**

Implement the `explore_pandas_dataframe` function. A `pd.DataFrame` is predefined inside the function body - **do not modify it**. Apply the correct `pandas` methods and return the results as a tuple.

The function must return a tuple of **8** elements in exactly this order:

1. `head_3` (`pd.DataFrame`): First **3** rows.
2. `tail_2` (`pd.DataFrame`): Last **2** rows.
3. `shape` (`tuple`): Shape of the DataFrame.
4. `col_names` (`list`): List of column names.
5. `dtypes` (`pd.Series`): Data type of each column.
6. `null_per_col` (`pd.Series`): Count of null values per column.
7. `describe_result` (`pd.DataFrame`): Summary statistics.
8. `mem_total` (`int`): Total memory in bytes using.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
  **For `head_3`:** Use the `pd.DataFrame` method that returns the first `n` rows, passing the desired number of rows as an argument.

  **For `tail_2`:** Use the `pd.DataFrame` method that returns the last `n` rows, passing the desired number of rows as an argument.

  **For `shape`:** Use the `pd.DataFrame` attribute that returns a tuple of `(number_of_rows, number_of_columns)`.

  **For `col_names`:** Use the `pd.DataFrame` attribute that holds column labels, then chain a method to convert it to a plain Python list.

  **For `dtypes`:** Use the `pd.DataFrame` attribute that returns the data type of each column as a `pd.Series`.

  **For `null_per_col`:** Recall that null detection in `pandas` can be done with a method that returns a boolean `pd.DataFrame`, and then another method can aggregate those booleans column-wise into counts.

  **For `describe_result`:** Use the `pd.DataFrame` method that computes summary statistics (count, mean, std, min, quartiles, max) for numeric columns.

  **For `mem_total`:** Use the `pd.DataFrame` method that returns memory usage per column as a `pd.Series`, passing `deep=True` to account for object types, then aggregate with `.sum()`.

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>

  **For `head_3`:** Use the following code:
  ```py
  head_3 = df.head(3)
  ```

  **For `tail_2`:** Use the following code:
  ```py
  tail_2 = df.tail(2)
  ```

  **For `shape`:** Use the following code:
  ```py
  shape = df.shape
  ```

  **For `col_names`:** Use the following code:
  ```py
  col_names = df.columns.tolist()
  ```

  **For `dtypes`:** Use the following code:
  ```py
  dtypes = df.dtypes
  ```

  **For `null_per_col`:** Use the following code:
  ```py
  null_per_col = df.isna().sum()
  ```

  **For `describe_result`:** Use the following code:
  ```py
  describe_result = df.describe()
  ```

  **For `mem_total`:** Use the following code:
  ```py
  mem_total = df.memory_usage(deep=True).sum()
  ```

  </details>

</details>

In [248]:
# GRADED FUNCTION: explore_pandas_dataframe
def explore_pandas_dataframe() -> tuple:
    """Explores a predefined pd.DataFrame using various pandas methods.

    Returns:
        tuple: A tuple of 8 elements:
            - head_3 (pd.DataFrame): First 3 rows.
            - tail_2 (pd.DataFrame): Last 2 rows.
            - shape (tuple): Shape (n_rows, n_cols).
            - col_names (list): List of column names.
            - dtypes (pd.Series): Data type of each column.
            - null_per_col (pd.Series): Count of null values per column.
            - describe_result (pd.DataFrame): Summary statistics.
            - mem_total (int): Total memory usage in bytes.
    """
    # Predefined data - do not modify this block
    df = pd.DataFrame({
        "name":       ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"],
        "age":        [25.0, 30.0, 35.0, 28.0, None, 22.0],
        "salary":     [50000.0, 60000.0, 70000.0, None, 48000.0, 52000.0],
        "department": ["HR", "Engineering", "Engineering", "Marketing", "HR", None],
        "score":      [88.0, 95.0, None, 76.0, 82.0, 90.0],
    })

    ### START CODE HERE ###

    head_3 = df.head(3)
    tail_2 = df.tail(2)
    shape = df.shape
    col_names = df.columns.tolist()
    dtypes = df.dtypes
    null_per_col = df.isna().sum()
    describe_result = df.describe()
    mem_total = df.memory_usage(deep=True).sum()

    ### END CODE HERE ###

    return (head_3, tail_2, shape, col_names, dtypes, null_per_col, describe_result, mem_total)

In [249]:
head_3, tail_2, shape, col_names, dtypes, null_per_col, describe_result, mem_total = explore_pandas_dataframe()

In [250]:
# First 3 rows
head_3

      name   age   salary   department  score
0    Alice  25.0  50000.0           HR   88.0
1      Bob  30.0  60000.0  Engineering   95.0
2  Charlie  35.0  70000.0  Engineering    NaN

In [251]:
# Last 2 rows
tail_2

    name   age   salary department  score
4    Eve   NaN  48000.0         HR   82.0
5  Frank  22.0  52000.0        NaN   90.0

In [252]:
# Shape and column names
print(f"Shape: {shape}")
print(f"Columns: {col_names}")

Shape: (6, 5)
Columns: ['name', 'age', 'salary', 'department', 'score']

In [253]:
# Data types
print("Data types (dtypes):")
print(dtypes)

Data types (dtypes):
name              str
age           float64
salary        float64
department        str
score         float64
dtype: object

In [254]:
# Null values per column
null_per_col

name          0
age           1
salary        1
department    1
score         1
dtype: int64

In [255]:
# Summary statistics
describe_result

             age        salary      score
count   5.000000      5.000000   5.000000
mean   28.000000  56000.000000  86.200000
std     4.949747   9055.385138   7.362065
min    22.000000  48000.000000  76.000000
25%    25.000000  50000.000000  82.000000
50%    28.000000  52000.000000  88.000000
75%    30.000000  60000.000000  90.000000
max    35.000000  70000.000000  95.000000

In [256]:
# Total memory usage (bytes)
print(f"Total memory: {mem_total} bytes")

Total memory: 910 bytes

In [257]:
# Test your implementation
unittests.exercise_2(explore_pandas_dataframe)

 All tests passed!

<a name='3---data-selection'></a>
## 3 - Data Selection

One of the most common operations on a `pd.DataFrame` is selecting specific subsets of data - particular columns, specific rows, or individual values. `pandas` provides multiple ways to do this, and choosing the right one depends on whether you are selecting by position or by label.

<a name='31---column-selection'></a>
### 3.1 Column Selection

Columns can be selected using bracket notation:

* **Single column** -> returns a `pd.Series`: `df["column_name"]`
* **Multiple columns** -> returns a `pd.DataFrame`: `df[["col1", "col2"]]`

In [258]:
# Extract a particular column from pd.DataFrame
species_s: pd.Series = sample_predef_df["species"]
species_s

0      versicolor
1          setosa
2       virginica
3      versicolor
4      versicolor
          ...
145    versicolor
146     virginica
147        setosa
148    versicolor
149     virginica
Name: species, Length: 150, dtype: str

In [259]:
# Single column -> pd.Series
print("Single column (pd.Series):")
species_s.head(3)

Single column (pd.Series):

0    versicolor
1        setosa
2     virginica
Name: species, dtype: str

In [260]:
# Extract a multiple columns from pd.DataFrame
two_cols_df: pd.DataFrame = sample_predef_df[["sepalLength", "sepalWidth"]]
two_cols_df

     sepalLength  sepalWidth
0            6.1         2.8
1            5.7         3.8
2            7.7         2.6
3            6.0         2.9
4            6.8         2.8
..           ...         ...
145          6.1         2.8
146          4.9         2.5
147          5.8         4.0
148          5.8         2.6
149          7.1         3.0

[150 rows x 2 columns]

In [261]:
# Multiple columns -> pd.DataFrame
print("Multiple columns (pd.DataFrame):")
two_cols_df.head(3)

Multiple columns (pd.DataFrame):

   sepalLength  sepalWidth
0          6.1         2.8
1          5.7         3.8
2          7.7         2.6

<a name='32---iloc-selection'></a>
### 3.2 Positional Selection with `.iloc[]`

`.iloc[]` selects data by **integer position** (zero-based index). It follows the same slicing rules as Python lists:

```py
df.iloc[row_indexer, col_indexer]
```

| Expression | Meaning |
|---|---|
| `df.iloc[0]` | First row |
| `df.iloc[:5]` | First 5 rows |
| `df.iloc[10:21]` | Rows at positions 10 to 20 (inclusive) |
| `df.iloc[-3:]` | Last 3 rows |
| `df.iloc[:, 0]` | First column (all rows) |
| `df.iloc[-3:, :2]` | Last 3 rows and first 2 columns |

In [262]:
# First 5 rows as pd.DataFrame
print("First 5 rows (df.iloc[:5]):")
sample_predef_df.iloc[:5]

First 5 rows (df.iloc[:5]):

   sepalLength  sepalWidth  petalLength  petalWidth     species
0          6.1         2.8          4.7         1.2  versicolor
1          5.7         3.8          1.7         0.3      setosa
2          7.7         2.6          6.9         2.3   virginica
3          6.0         2.9          4.5         1.5  versicolor
4          6.8         2.8          4.8         1.4  versicolor

In [263]:
# Rows at positions 10 to 20 (inclusive)
print("Rows 10-20 (df.iloc[10:21]):")
sample_predef_df.iloc[10:21]

Rows 10-20 (df.iloc[10:21]):

    sepalLength  sepalWidth  petalLength  petalWidth     species
10          6.5         3.2          5.1         2.0   virginica
11          4.8         3.0          1.4         0.1      setosa
12          5.5         3.5          1.3         0.2      setosa
13          4.9         3.1          1.5         0.1      setosa
14          5.1         3.8          1.5         0.3      setosa
15          6.3         3.3          4.7         1.6  versicolor
16          6.5         3.0          5.8         2.2   virginica
17          5.6         2.5          3.9         1.1  versicolor
18          5.7         2.8          4.5         1.3  versicolor
19          6.4         2.8          5.6         2.2   virginica
20          4.7         3.2          1.6         0.2      setosa

In [264]:
# Last 3 rows, first 2 columns
print("Last 3 rows, first 2 columns (df.iloc[-3:, :2]):")
sample_predef_df.iloc[-3:, :2]

Last 3 rows, first 2 columns (df.iloc[-3:, :2]):

     sepalLength  sepalWidth
147          5.8         4.0
148          5.8         2.6
149          7.1         3.0

<a name='33---loc-selection'></a>
### 3.3 Label-Based Selection with `.loc[]`

`.loc[]` selects data by **label** (row index label or column name). Unlike `.iloc[]`, when slicing with `.loc[]`, the stop label is **inclusive**:

```py
df.loc[row_label, col_label]
```

| Expression | Meaning |
|---|---|
| `df.loc[0, "sepalLength"]` | Single value at row label 0, column "sepalLength" |
| `df.loc[0:4]` | Rows with labels 0 to 4 (inclusive) |
| `df.loc[:, "sepalLength"]` | All rows, only "sepalLength" column |

In [265]:
# Single value
val = sample_predef_df.loc[0, "sepalLength"]
print(f"Value at row 0, 'sepalLength' (df.loc[0, 'sepalLength']): {val}")

Value at row 0, 'sepalLength' (df.loc[0, 'sepalLength']): 6.1

In [266]:
# Rows 0 to 4 (inclusive in .loc)
print("Rows 0 to 4 (df.loc[0:4]):")
print(sample_predef_df.loc[0:4])

Rows 0 to 4 (df.loc[0:4]):
   sepalLength  sepalWidth  petalLength  petalWidth     species
0          6.1         2.8          4.7         1.2  versicolor
1          5.7         3.8          1.7         0.3      setosa
2          7.7         2.6          6.9         2.3   virginica
3          6.0         2.9          4.5         1.5  versicolor
4          6.8         2.8          4.8         1.4  versicolor

<a name='34---boolean-filtering'></a>
### 3.4 Boolean Filtering

Boolean filtering selects rows where a condition evaluates to `True`. The condition creates a boolean `pd.Series` which is then used to index the DataFrame:

```py
df[df["column"] == "value"]         # equality
df[df["column"] > threshold]        # comparison
df[(cond_1) & (cond_2)]             # multiple conditions (AND)
df[(cond_1) | (cond_2)]             # multiple conditions (OR)
```

In [267]:
# Select only setosa species
setosa_df: pd.DataFrame = sample_predef_df[sample_predef_df["species"] == "setosa"]
setosa_df

     sepalLength  sepalWidth  petalLength  petalWidth species
1            5.7         3.8          1.7         0.3  setosa
5            5.4         3.4          1.5         0.4  setosa
11           4.8         3.0          1.4         0.1  setosa
12           5.5         3.5          1.3         0.2  setosa
13           4.9         3.1          1.5         0.1  setosa
14           5.1         3.8          1.5         0.3  setosa
20           4.7         3.2          1.6         0.2  setosa
22           5.0         3.4          1.6         0.4  setosa
28           4.8         3.0          1.4         0.3  setosa
29           4.8         3.1          1.6         0.2  setosa
30           4.6         3.6          1.0         0.2  setosa
31           5.7         4.4          1.5         0.4  setosa
33           4.8         3.4          1.6         0.2  setosa
34           4.4         3.2          1.3         0.2  setosa
37           5.2         3.5          1.5         0.2  setosa
38           5.0         3.6          1.4         0.2  setosa
39           5.2         4.1          1.5         0.1  setosa
43           5.4         3.9          1.3         0.4  setosa
44           5.4         3.7          1.5         0.2  setosa
53           5.1         3.5          1.4         0.2  setosa
56           5.2         3.4          1.4         0.2  setosa
57           5.0         3.5          1.3         0.3  setosa
58           5.1         3.8          1.9         0.4  setosa
61           4.8         3.4          1.9         0.2  setosa
62           5.0         3.0          1.6         0.2  setosa
63           5.1         3.3          1.7         0.5  setosa
65           5.1         3.4          1.5         0.2  setosa
68           4.6         3.2          1.4         0.2  setosa
71           5.5         4.2          1.4         0.2  setosa
78           5.4         3.9          1.7         0.4  setosa
81           5.0         3.3          1.4         0.2  setosa
82           5.0         3.2          1.2         0.2  setosa
85           4.9         3.1          1.5         0.2  setosa
87           5.0         3.4          1.5         0.2  setosa
88           5.0         3.5          1.6         0.6  setosa
96           4.4         2.9          1.4         0.2  setosa
97           4.3         3.0          1.1         0.1  setosa
100          4.6         3.1          1.5         0.2  setosa
101          5.1         3.5          1.4         0.3  setosa
102          4.4         3.0          1.3         0.2  setosa
105          4.6         3.4          1.4         0.3  setosa
108          4.7         3.2          1.3         0.2  setosa
114          5.1         3.8          1.6         0.2  setosa
121          4.5         2.3          1.3         0.3  setosa
124          5.3         3.7          1.5         0.2  setosa
128          5.1         3.7          1.5         0.4  setosa
132          4.9         3.6          1.4         0.1  setosa
134          4.9         3.0          1.4         0.2  setosa
144          5.4         3.4          1.7         0.2  setosa
147          5.8         4.0          1.2         0.2  setosa

In [268]:
# Extract first 3 rows of the subset of data where only setosa species are listed
print(f"Setosa rows: {setosa_df.shape[0]} (out of {sample_predef_df.shape[0]})")
setosa_df.head(3)

Setosa rows: 50 (out of 150)

    sepalLength  sepalWidth  petalLength  petalWidth species
1           5.7         3.8          1.7         0.3  setosa
5           5.4         3.4          1.5         0.4  setosa
11          4.8         3.0          1.4         0.1  setosa

In [269]:
# Combine conditions: species == setosa AND sepalLength > 5
filtered: pd.DataFrame = sample_predef_df[
    (sample_predef_df["species"] == "setosa") & (sample_predef_df["sepalLength"] > 5)
]
filtered

     sepalLength  sepalWidth  petalLength  petalWidth species
1            5.7         3.8          1.7         0.3  setosa
5            5.4         3.4          1.5         0.4  setosa
12           5.5         3.5          1.3         0.2  setosa
14           5.1         3.8          1.5         0.3  setosa
31           5.7         4.4          1.5         0.4  setosa
37           5.2         3.5          1.5         0.2  setosa
39           5.2         4.1          1.5         0.1  setosa
43           5.4         3.9          1.3         0.4  setosa
44           5.4         3.7          1.5         0.2  setosa
53           5.1         3.5          1.4         0.2  setosa
56           5.2         3.4          1.4         0.2  setosa
58           5.1         3.8          1.9         0.4  setosa
63           5.1         3.3          1.7         0.5  setosa
65           5.1         3.4          1.5         0.2  setosa
71           5.5         4.2          1.4         0.2  setosa
78           5.4         3.9          1.7         0.4  setosa
101          5.1         3.5          1.4         0.3  setosa
114          5.1         3.8          1.6         0.2  setosa
124          5.3         3.7          1.5         0.2  setosa
128          5.1         3.7          1.5         0.4  setosa
144          5.4         3.4          1.7         0.2  setosa
147          5.8         4.0          1.2         0.2  setosa

In [270]:
# Extract a rows with sepalLength feature higher than 5
print(f"Setosa with sepalLength > 5: {filtered.shape[0]} rows")
filtered.head(3)

Setosa with sepalLength > 5: 22 rows

    sepalLength  sepalWidth  petalLength  petalWidth species
1           5.7         3.8          1.7         0.3  setosa
5           5.4         3.4          1.5         0.4  setosa
12          5.5         3.5          1.3         0.2  setosa

<a name='exercise-3---select-from-dataframe'></a>
### **Exercise 3 - `select_from_dataframe`**

**Your Task:**

Implement the `select_from_dataframe` function. The Iris DataFrame is <b><font color="red">NOT</font></b> loaded automatically. Recall what you have learned from previous lesson. Take into consideration that you are given the path to JSON dataset file and JSON internal format/structure (`orient` type). Apply the correct selection methods and return the results as a tuple.

The function must return a tuple of **7** elements in exactly this order:

1. `species_col` (`pd.Series`): The `'species'` column.
2. `two_cols` (`pd.DataFrame`): A DataFrame with `'sepalLength'` and `'sepalWidth'` columns.
3. `first_5_rows` (`pd.DataFrame`): First **5** rows using `.iloc`.
4. `rows_10_to_20` (`pd.DataFrame`): Rows at positions **10 to 20** (inclusive) using `.iloc`.
5. `specific_value`: The value at row label `0`, column `'sepalLength'` using `.loc`.
6. `setosa_rows` (`pd.DataFrame`): Rows where `species` is represented as `'setosa'` using boolean filtering.
7. `last3_first2` (`pd.DataFrame`): Last **3** rows and first **2** columns using `.iloc`.

<details>
<summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>

**For `df`**: Load dataset from a json file (NOT LINES) located at `path_to_json_file` into a `pd.DataFrame`, with orient type specified as suggested (use `orient_type`)

**For `species_col`:** It can be done in the similar way as classical access of a value from a python dictionary using its key.

**For `two_cols`:** It can be done in the similar way as classical access of a value from a python dictionary using its key, but treat the "key" as a list of column names.

**For `first_5_rows`:** It can be done in the same way as indexing a python list with end value. Use index location.

**For `rows_10_to_20`:** It can be done in the same way as indexing a python list with start and end values. Use index location.

**For `specific_value`:** Use label-based indexing with specified index of the desired row and column name.

**For `setosa_rows`:** Recall how boolean filtering was covered in the materials and how a conditional with a `pandas` data structure with a specific value results in a `pd.Series` with boolean values per each row evaluating the desired column with the condition. Use square bracket indexing.

**For `last3_first2`:** Recall how rows and columns indices can be used both at the same time in index-based selection.

<details>
<summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>

    **For `df`**: Use the following code:
    ```py
    df = pd.read_json(path_or_buf=path_to_json_file, orient=orient_type, lines=False)
    ```

    **For `species_col`:** Use the following code:
    ```py
    species_col = df["species"]
    ```

    **For `two_cols`:** Use the following code:
    ```py
    two_cols = df[["sepalLength", "sepalWidth"]]
    ```

    **For `first_5_rows`:** Use the following code:
    ```py
    first_5_rows = df.iloc[:5]
    ```

    **For `rows_10_to_20`:** Use the following code:
    ```py
    rows_10_to_20 = df.iloc[10:21]
    ```

    **For `specific_value`:** Use the following code:
    ```py
    specific_value = df.loc[0, "sepalLength"]
    ```

    **For `setosa_rows`:** Use the following code:
    ```py
    setosa_rows = df[df["species"] == "setosa"]
    ```

    **For `last3_first2`:** Use the following code:
    ```py
    last3_first2 = df.iloc[-3:, :2]
    ```
</details>

</details>

In [271]:
# GRADED FUNCTION: select_from_dataframe
def select_from_dataframe() -> tuple:
    """Loads the Iris dataset and applies various data selection techniques.

    Returns:
        tuple: A tuple of 7 elements:
            - species_col (pd.Series): The 'species' column.
            - two_cols (pd.DataFrame): 'sepalLength' and 'sepalWidth' columns.
            - first_5_rows (pd.DataFrame): First 5 rows using .iloc.
            - rows_10_to_20 (pd.DataFrame): Rows at positions 10-20 using .iloc.
            - specific_value: Value at row 0, column 'sepalLength', using .loc.
            - setosa_rows (pd.DataFrame): Rows where species is represented as 'setosa'.
            - last3_first2 (pd.DataFrame): Last 3 rows and first 2 columns using .iloc.
    """
    path_to_json_file = helper_utils.return_json_file_path()
    orient_type = helper_utils.return_json_file_orient_type()

    ### START CODE HERE ###
    df = pd.read_json(path_or_buf=path_to_json_file, orient=orient_type, lines=False)
    
    species_col = df["species"]
    two_cols = df[["sepalLength", "sepalWidth"]]
    first_5_rows = df.iloc[:5]
    rows_10_to_20 = df.iloc[10:21]
    specific_value = df.loc[0, "sepalLength"]
    setosa_rows = df[df["species"] == "setosa"]
    last3_first2 = df.iloc[-3:, :2]

    ### END CODE HERE ###

    return (species_col, two_cols, first_5_rows, rows_10_to_20, specific_value, setosa_rows, last3_first2)

In [272]:
species_col, two_cols, first_5_rows, rows_10_to_20, specific_value, setosa_rows, last3_first2 = select_from_dataframe()

In [273]:
# 'species' column as pd.Series
species_col

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [274]:
# Two columns as pd.DataFrame
two_cols

     sepalLength  sepalWidth
0            5.1         3.5
1            4.9         3.0
2            4.7         3.2
3            4.6         3.1
4            5.0         3.6
..           ...         ...
145          6.7         3.0
146          6.3         2.5
147          6.5         3.0
148          6.2         3.4
149          5.9         3.0

[150 rows x 2 columns]

In [275]:
# First 5 rows
print("First 5 rows:")
first_5_rows

First 5 rows:

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [276]:
# Rows 10 to 20
print("Rows 10 to 20:")
rows_10_to_20

Rows 10 to 20:

    sepalLength  sepalWidth  petalLength  petalWidth species
10          5.4         3.7          1.5         0.2  setosa
11          4.8         3.4          1.6         0.2  setosa
12          4.8         3.0          1.4         0.1  setosa
13          4.3         3.0          1.1         0.1  setosa
14          5.8         4.0          1.2         0.2  setosa
15          5.7         4.4          1.5         0.4  setosa
16          5.4         3.9          1.3         0.4  setosa
17          5.1         3.5          1.4         0.3  setosa
18          5.7         3.8          1.7         0.3  setosa
19          5.1         3.8          1.5         0.3  setosa
20          5.4         3.4          1.7         0.2  setosa

In [277]:
# Single value
print(f"Value at row 0, 'sepalLength': {specific_value}")

Value at row 0, 'sepalLength': 5.1

In [278]:
# Setosa rows (first 3)
print(f"Setosa rows ({len(setosa_rows)} total):")
setosa_rows.head(3)

Setosa rows (50 total):

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa

In [279]:
# Last 3 rows, first 2 columns
print("Last 3 rows, first 2 columns:")
last3_first2

Last 3 rows, first 2 columns:

     sepalLength  sepalWidth
147          6.5         3.0
148          6.2         3.4
149          5.9         3.0

In [280]:
# Test your implementation
unittests.exercise_3(select_from_dataframe)

 All tests passed!

<a name='4---groupby-aggregation'></a>
## 4 - GroupBy and Aggregation

Grouping data by categorical columns and then computing statistics per group is one of the most powerful analytical operations in `pandas`. The main method is `.groupby()`:

```py
df.groupby("group_column")["target_column"].aggregation_function()
```

After `.groupby()`, the result is a `DataFrameGroupBy` or `SeriesGroupBy` object. You then apply an aggregation method (`.mean()`, `.size()`, `.agg()`, etc.) to compute the statistic per group.

<a name='41---groupby'></a>
### 4.1 Grouping with `.groupby()`

`.groupby()` splits the DataFrame into groups based on unique values in one or more columns, then applies any aggregation method to each group:

In [281]:
# Mean sepalLength per species
print("Mean sepalLength per species:")
print(sample_predef_df.groupby("species")["sepalLength"].mean())

Mean sepalLength per species:
species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepalLength, dtype: float64

In [282]:
# Mean of ALL numeric columns per species
print("Mean of all numeric columns per species:")
print(sample_predef_df.groupby("species").mean(numeric_only=True))

Mean of all numeric columns per species:
            sepalLength  sepalWidth  petalLength  petalWidth
species
setosa            5.006       3.428        1.462       0.246
versicolor        5.936       2.770        4.260       1.326
virginica         6.588       2.974        5.552       2.026

<a name='42---group-sizes'></a>
### 4.2 Counting Group Sizes

`.size()` returns the number of rows in each group as a `pd.Series`:

In [283]:
# Number of rows per species
print("Row count per species (.groupby().size()):")
print(sample_predef_df.groupby("species").size())

Row count per species (.groupby().size()):
species
setosa        50
versicolor    50
virginica     50
dtype: int64

<a name='43---agg'></a>
### 4.3 Multiple Aggregations with `.agg()`

`.agg()` allows computing **multiple statistics** at once for a given column, returning a `pd.DataFrame` with one column per aggregation function:

```py
df.groupby("group_col")["target_col"].agg(["mean", "std", "min", "max"])
```

In [284]:
# Multiple aggregations for sepalLength per species
print("sepalLength statistics per species (.agg()):")
sample_predef_df.groupby("species")["sepalLength"].agg(["mean", "std", "min", "max"])

sepalLength statistics per species (.agg()):

             mean       std  min  max
species
setosa      5.006  0.352490  4.3  5.8
versicolor  5.936  0.516171  4.9  7.0
virginica   6.588  0.635880  4.9  7.9

<a name='exercise-4---groupby-and-aggregate'></a>
### **Exercise 4 - `groupby_and_aggregate`**

**Your Task:**

Implement the `groupby_and_aggregate` function. The Iris DataFrame is <b><font color="red">NOT</font></b> loaded automatically. Recall what you have learned from previous lesson. Take into consideration that you are given the path to JSON dataset file and JSON internal format/structure (`orient` type). Apply the correct groupby and aggregation methods and return the results as a tuple.

The function must return a tuple of **4** elements in exactly this order:

1. `mean_sepal_by_species` (`pd.Series`): Mean of `'sepalLength'` grouped by `'species'`.
2. `count_per_species` (`pd.Series`): Count the number of rows group by `'species'`.
3. `agg_sepal_length` (`pd.DataFrame`): Mean and standard deviation of `'sepalLength'` per `'species'`.
4. `mean_all_numeric` (`pd.DataFrame`): Mean of all **numeric** columns per `'species'`.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>

  **For `df`**: Load dataset from a json file (NOT LINES) located at `path_to_json_file` into a `pd.DataFrame`, with orient type specified as suggested (use `orient_type`)

  **For `mean_sepal_by_species`:** Selecting a specific column from the dataset can be done in similar way as accessing a value from a python dictionary. Recall what function is used for calculating the mean of a structure and how to group rows from a `pd.DataFrame`.

  **For `count_per_species`:** Recall how to group rows from a `pd.DataFrame` and use `.size()` method to calculate the number of rows per each category that was grouped.

  **For `agg_sepal_length`:** Recall how to group rows from a `pd.DataFrame`. Selecting a specific column from the dataset can be done in similar way as accessing a value from a python dictionary. Remember how can multiple statistics computed using `pandas` built-in methods using aggregation.

  **For `mean_all_numeric`:** Recall how to group rows from a `pd.DataFrame`. Remember what argument is used when calculating `.mean()` in order to avoid non-numerical columns
  
  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>
  
  **For `df`**: Use the following code:
  ```py
  df = pd.read_json(path_or_buf=path_to_json_file, orient=orient_type, lines=False)
  ```

  **For `mean_sepal_by_species`:** Use the following code:
  ```py
  mean_sepal_by_species = df.groupby("species")["sepalLength"].mean()
  ```

  **For `count_per_species`:** Use the following code:
  ```py
  count_per_species = df.groupby("species").size()
  ```

  **For `agg_sepal_length`:** Use the following code:
  ```py
  agg_sepal_length = df.groupby("species")["sepalLength"].agg(["mean", "std"])
  ```

  **For `mean_all_numeric`:** Use the following code:
  ```py
  mean_all_numeric = df.groupby("species").mean(numeric_only=True)
  ```

  </details>

</details>

In [285]:
# GRADED FUNCTION: groupby_and_aggregate
def groupby_and_aggregate() -> tuple:
    """Loads the Iris dataset and applies groupby and aggregation techniques.

    Returns:
        tuple: A tuple of 4 elements:
            - mean_sepal_by_species (pd.Series): Mean sepalLength grouped by species.
            - count_per_species (pd.Series): Row count per species group.
            - agg_sepal_length (pd.DataFrame): Mean and standard deviation of sepalLength per species.
            - mean_all_numeric (pd.DataFrame): Mean of all numeric columns per species.
    """
    path_to_dataset = helper_utils.return_json_file_path()
    orient_type = helper_utils.return_json_file_orient_type()
    
    ### START CODE HERE ###
    df = pd.read_json(path_or_buf=path_to_dataset, orient=orient_type, lines=False)
    
    mean_sepal_by_species = df.groupby("species")["sepalLength"].mean()
    count_per_species = df.groupby("species").size()
    agg_sepal_length = df.groupby("species")["sepalLength"].agg(["mean", "std"])
    mean_all_numeric = df.groupby("species").mean(numeric_only=True)

    ### END CODE HERE ###

    return (mean_sepal_by_species, count_per_species, agg_sepal_length, mean_all_numeric)

In [286]:
mean_sepal_by_species, count_per_species, agg_sepal_length, mean_all_numeric = groupby_and_aggregate()

In [287]:
# Mean sepalLength per species
mean_sepal_by_species

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepalLength, dtype: float64

In [288]:
# Row count per species
count_per_species

species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [289]:
# Mean and std of sepalLength per species
agg_sepal_length

             mean       std
species
setosa      5.006  0.352490
versicolor  5.936  0.516171
virginica   6.588  0.635880

In [290]:
# Mean of all numeric columns per species
mean_all_numeric

            sepalLength  sepalWidth  petalLength  petalWidth
species
setosa            5.006       3.428        1.462       0.246
versicolor        5.936       2.770        4.260       1.326
virginica         6.588       2.974        5.552       2.026

In [291]:
# Test your implementation
unittests.exercise_4(groupby_and_aggregate)

 All tests passed!

## Conclusion

Congratulations! You have successfully completed the First Data Interaction assignment.

In this assignment, you explored how real-world datasets can be explored as an initial step before applying any transformations to understand and gather basic insights into how data may relate one to each other, what data types are contained inside a dataset, the range of values per each feature etc.

With these basic statistics and data manipulation techniques, you now have a way to easily and swiftly gather knowledge about the data you are going to work, providing useful information for future steps of transforming, cleaning, normalizing and so on.