# Programming Assignment: Multi-Format Data Loading

Welcome to the assignment for Multi-Format Data Loading.

Data is a raw or basic collection of observations, measurements, facts etc. that is used to represent and describe objects, phenomena and events. On the other hand, datasets are organized pieces of data, that are typically related to a specific domain or have some common logic behind their organization. Data and datasets provide probably the most important and crucial details without which machine learning could not evolve so much over the years. One of the most important things about high-quality data is that it provides a way for machine learning models to "learn", or find underlying patterns and relations between various pieces of data.

Datasets can originate from various sources, such as: experiments, surveys, systems logs, sensors, databases and many others. They vary in size and format. Usually, datasets are organized based on structurality. By this criterion, datasets can be:
1. **Structured** - highly organized/formatted data represented in strict predefined format (with a strict "schema"). Usually, this type of data is represented in Relational Databases, CSV/Excel files and others. Below is represented an example of a dataset organized in tabular format:

    | **ID** | **Age** | **Body_Mass_Index** | **Gender** | **Blood_Type** | **...** | **Is_Sick** |
    |:------:|:-------:|:-------------------:|:----------:|:--------------:|:-------:|:-----------:|
    |   _1_  |    18   |          40         |     "M"    |      "AB+"     |   ...   |     True    |
    |   _2_  |    35   |          27         |    None    |       "O"      |   ...   |    False    |
    |   _3_  |    24   |          31         |     "F"    |      None      |   ...   |    False    |
    |  _..._ |   ...   |         ...         |     ...    |       ...      |   ...   |     ...     |
    | _1000_ |    95   |          35         |     "F"    |      "A-"      |   ...   |     True    |

2. **Semi-Structured** - data that have some organizational properties, with flexible "schema", that may differ from dataset record to record. Most of the time, this type of datasets is represented in JSON, XML, system logs and other formats. Below is represented an example of such JSON dataset (Note differences in these records):

    ```json
    {
        "name": "John",
        "age": 20,
        "interests": ["Literature", "Music Production"],
        "num_requests": 201,
        "is_subscribed": "True"
    },
    {
        "name": "Jane",
        "age": "None",
        "interests": ["Literature", "Music Production"],
        "is_subscribed": "False",
        "location": "Europe"
    },
    ...
    ```

3. **Unstructured** - data that contain information that is does not conform to traditional data models, with no "schema". This type of datasets can be represented in various ways: videos/audio/text files, chat messages, etc. This category is the hardest to work with, but most of the time, they capture rich insights and information. 

Most of Machine Learning application involve working with structured datasets, however datasets of other two types are also used, but require more preparation and deeper understanding of complex loading and processing mechanisms. For the start, being able to work with datasets involve being able to load them properly into data structures that can be manipulated/actioned on via programming. One of the most popular libraries that offer this possibility is [`pandas`](https://pandas.pydata.org/docs/index.html). [`pandas`](https://pandas.pydata.org/docs/index.html) is an open-source data analysis and manipulation tool, built on top of `Python` programming language, that is able to convert data from files into data structures that can be interacted with via code. This library offers two main data structures that can be used to represent tabular data:
1. `Series` - one-dimensional labeled array holding data of any type. This structure can be interpreted as a basic list. For example:

    | **ID** |
    |:------:|
    |   _1_  |
    |   _2_  |
    |   _3_  |
    |  _..._ |
    | _1000_ |

2. `DataFrame` - two-dimensional data structure that holds data like a two-dimensional array. In other words, this is a basic table with rows and columns. For example, recall previous structured dataset example:

    | **ID** | **Age** | **Body_Mass_Index** |
    |:------:|:-------:|:-------------------:|
    |   _1_  |    18   |          40         |
    |   _2_  |    35   |          27         |
    |   _3_  |    24   |          31         |
    |  _..._ |   ...   |         ...         |
    | _1000_ |    95   |          35         |


In this assignment, you'll understand and apply basic `pandas` data loading techniques on various data from different file formats. 

**What You will do in this Assignment**

* Learn how to read CSV files into `pandas` `DataFrames` using appropriate parameters for delimiters, headers, and names.
* Load Excel workbooks and sheets into `pandas` while handling mixed data types and missing values.
* Import `JSON` data, including nested structures, and load it into tabular `DataFrames`.
* Retrieve data from `SQL` databases using `pandas` database connectors and convert query results into `DataFrames`.
* Fetch data from web APIs, parse the responses, and load them into `pandas` structures.

Let's get started!

---
<a name='submission'></a>

<h4 style="color:green; font-weight:bold;">TIPS FOR SUCCESSFUL GRADING OF YOUR ASSIGNMENT:</h4>

* All cells are frozen except for the ones where you need to submit your solutions or when explicitly mentioned you can interact with it.

* In each exercise cell, look for comments `### START CODE HERE ###` and `### END CODE HERE ###`. These show you where to write the solution code. **Do not add or change any code that is outside these comments**.

* You can add new cells to experiment but these will be omitted by the grader, so don't rely on newly created cells to host your solution code, use the provided places for this.

---

## Table of Contents
- [Imports](#imports)
- [Prerequisites](#prerequisites)
- [1 - Introduction to pandas Data Structures](#1---series-dataframe)
    - [1.1 - Introduction to `pd.Series`](#11---series)
        - **[Exercise 1 - Create Pandas Series](#exercise-1---create-pandas-series)**
    - [1.2 - Introduction to `pd.DataFrame`](#12---dataframe)
        - **[Exercise 2 - Create Pandas DataFrames](#exercise-2---create-pandas-dataframes)**
- [2 - Loading from CSV file](#2---csv-files)
    - [2.1 - Reading a `.csv` file using `pd.read_csv()`](#21---read-csv-files)
        - **[Exercise 3 - `read_from_csv`](#exercise-3---read-from-csv)**
- [3 - Loading from Excel file](#3---excel-files)
    - [3.1 - Reading a `.xlsx` file using `pd.read_excel()`](#31---read-excel-files)
        - **[Exercise 4 - `read_from_excel`](#exercise-4---read-from-excel)**
- [4 - Loading from JSON file](#4---json-files)
    - [4.1 - Reading a `.json` file using `pd.read_json()`](#41---read-json-files)
        - **[Exercise 5 - `read_from_json`](#exercise-5---read-from-json)**
- [5 - Loading from SQL Database](#5---sql-db)
    - [5.1 - Reading a table from SQL Database using `pd.read_sql()`](#51---read-sql-db)
        - **[Exercise 6 - `read_from_sql_db`](#exercise-6---read-from-sql-db)**

<a name='imports'></a>
## Imports

In [1]:
import pandas as pd
import numpy as np
from typing import Any
from pathlib import Path

In [2]:
from tqdm.auto import tqdm
import helper_utils
import unittests

<a name='prereqs'></a>
## Prerequisites
Before starting trying to load any dataset, it is required to first find (or produce) the dataset. This can be done via different services, as well as other sources - experiments, trials, personal observations. Since internet offers a way for people to share information with others, in the domain of Machine Learning, people use it to share different datasets as well, making them public and free-to-use. Take into consideration that, most of the time, to use qualitative and big datasets is required additional confirmation of how the dataset will be used, what are the goals that are trying to be achieved using a particular dataset and so on. 

However, for most of the ML applications, public datasets are more than enough. Some of the most influential platforms in sharing and publishing datasets are:
1. [**Kaggle**](https://www.kaggle.com/) - AI/ML Community Web platform that offers a way to share datasets, host and attend competitions, post notebooks with solutions for different tasks and access and study a lot of learning material. In order to view the dedicated pages for datasets, follow the link: [Kaggle Datasets](https://www.kaggle.com/datasets). Beginner-friendly, suitable for both beginners and advanced ML enthusiasts, with high focus on learning and participating in competitions.
2. [**HuggingFace**](https://huggingface.co/) - Similar AI/ML Community Web platform offering a place to host and share datasets, in a similar way [Github](https://github.com/) does (repository structure, file-versioning, etc.), access AI/ML open-source models, share your achievements in ML field and so on. To access the dataset section of the platform, follow the link: [HuggingFace Datasets](https://huggingface.co/datasets). Steeper "learning" curve, with strong focus more on sharing advancements and hosting models, AI/ML apps and datasets, sharing them with the community.
3. [**Github**](https://github.com/) - Although [Github](https://github.com/) is more a cloud-based platform that uses [Git](https://git-scm.com/) as a Version Control System rather than focusing on datasets hosting, people may publish datasets on this platform as well. You may search across different repositories the ones that are specifically stated as for hosting datasets. Try your luck on this platform as well.

In [3]:
# Create datasets folder/directory to store files with data
helper_utils.make_data_dir()

csv file datasets located at: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\csv
excel file datasets located at: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\excel
json file datasets located at: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\json
sql_db file datasets located at: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\sql_db

For simplicity, this notebook will automatically download the required datasets, in various formats (`.csv`, `xlsx`, `.json`, SQL Database). If you are interested into using other datasets, consult the mentioned websites and other APIs, and use appropriate `helper_utils` functions. 

<p style="color:red; font-weight:bold;">NOTE: Take into consideration that this Notebook is developed keeping in mind that default datasets are used. No automatic evaluation will be done in case you use other datasets than the one that are automatically downloaded.</p>

1. `.csv` - CSV dataset - Spotify Tracks Dataset - [AVAILABLE HERE](https://huggingface.co/datasets/maharshipandya/spotify-tracks-dataset)
2. `.xlsx` - Excel dataset - Avocado Prices Dataset - [AVAILABLE HERE](https://github.com/rohanmistry231/Practice-Datasets-for-Excel/tree/main/Avacado%20Prices)
3. `.json` - JSON dataset - Iris Dataset - [AVAILABLE HERE](https://www.kaggle.com/datasets/rtatman/iris-dataset-json-version)
4. `.sql` - SQL DB dataset - Iris Dataset - Transformed into SQL Database - Generated at runtime automatically and populated with data from Iris JSON Dataset.

In [4]:
# Download different format files with data
helper_utils.download_all_datasets()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

<a name='1---series-dataframe'></a>
## 1 - `pd.DataFrame` and `pd.Series`
`pandas` library offers two main data structures - `pd.DataFrame` and `pd.Series`. They can be interpreted as two-dimensional array = `pd.DataFrame` and one-dimensional array - `pd.Series`. However, they have extensive utils that make them very useful when dealing with datasets.

Both structures can hold any values, just like python lists, but are compatible with other libraries, like `numpy`, meaning that when instantiating objects of `pd.DataFrame` and `pd.Series`, as their inputs, `numpy` arrays can be used. Don't worry if you are not familiar with this library, next lectures will shed some light on it. As of now, take this as a sign of how `pandas` library has inherent compatibility with other libraries.

<a name='11---series'></a>
### 1.1 Introduction to `pd.Series`
Series are formed of the following key elements:

1. **Data** – A one-dimensional array of values.
2. **Index** – Labels that identify each element in the Series.
3. **Name** - Name of the Series object.
3. **Dtype** – The data type of the values (e.g., `int64`, `float64`, `object`).

These structures can be instantiated in the following ways:

1. From a list or tuple
2. From a NumPy array
3. From a dictionary
4. From a scalar value (with a specified index)
5. From another Series or DataFrame column

In [5]:
# 1.1 Using a list
list_of_data: list[Any] = [1, "a", 3.2, [1, 2, 3]]

series_from_list: pd.Series = pd.Series(data=list_of_data, name='Sample_Data')
series_from_list

0            1
1            a
2          3.2
3    [1, 2, 3]
Name: Sample_Data, dtype: object

In [6]:
# 1.2 Using a tuple
tuple_of_data: tuple[Any] = (1, "a", 3.2, [1, 2, 3])

series_from_tuple: pd.Series = pd.Series(data=tuple_of_data, name='Sample_Data')
series_from_tuple

0            1
1            a
2          3.2
3    [1, 2, 3]
Name: Sample_Data, dtype: object

In [7]:
# 2. Using a numpy 1D array
one_d_np_array: np.ndarray = np.array(object=[1, 2, 3, 4, 5])

series_from_np_array: pd.Series = pd.Series(data=one_d_np_array, name="Sample_Data")
series_from_np_array

0    1
1    2
2    3
3    4
4    5
Name: Sample_Data, dtype: int64

In [8]:
# 3. Using a dictionary of values
# Dict keys represent indices of the Series
# Dict values represent values that are stored in the Series at their index
dict_of_data: dict[str, Any] = {
    "Index_A": [1, "A", 3.2],
    "Index_B": 1,
    "Index_C": "B"
}

series_from_dict: pd.Series = pd.Series(data=dict_of_data, name='Sample_Data')
series_from_dict

Index_A    [1, A, 3.2]
Index_B              1
Index_C              B
Name: Sample_Data, dtype: object

In [9]:
# 4. Using a scalar with index
# In this case, a single value can be propagated at more indices
value_to_propagate: Any = "VALUE"
length_indices: list[Any] = ["A", 1, "ANY"]

series_from_scalar: pd.Series = pd.Series(data=value_to_propagate, index=length_indices)
series_from_scalar

A      VALUE
1      VALUE
ANY    VALUE
dtype: str

In [10]:
# 5.1 Using another Series
series_orig: pd.Series = pd.Series(data=[10, 20, 30], name="C")

series_from_anth_series: pd.Series = pd.Series(data=series_orig) # or `series_orig.copy(deep=True/False)`
series_from_anth_series

0    10
1    20
2    30
Name: C, dtype: int64

In [11]:
# 5.2 Using a column from DataFrame
df_1: pd.DataFrame = pd.DataFrame(data=[[10, 20, 30], [20, 30, 40], [30, 40, 50]], columns=["Feature_1", "Feature_2", "Feature_3"])

series_from_anth_series: pd.Series = pd.Series(data=df_1["Feature_1"])  # You can access DataFrame by column names similar to list index access = df_1["Feature_1"]
series_from_anth_series

0    10
1    20
2    30
Name: Feature_1, dtype: int64

In [12]:
# You may also rename a specific index label/name using `rename()` method of `pd.Series`
series_orig: pd.Series = pd.Series(data=[10, 20, 30], index=["INDEX_1", "INDEX_2", "INDEX_3"], name="C")

new_series: pd.Series = series_orig.rename({"INDEX_1": "NEW_INDEX_NAME"})
new_series

NEW_INDEX_NAME    10
INDEX_2           20
INDEX_3           30
Name: C, dtype: int64

<a name='exercise-1---create-pandas-series'></a>
### **Exercise 1 - `create_pandas_series`**

**Your Task:**

Implement the `create_pandas_series` function that returns a tuple of 5 `pd.Series` created using different methods:

1. `ser_1`: A `pd.Series` named `"SERIES_FROM_LIST"` using a **python list** with the following values: `[10, 20, 30, 40, 50]`.
2. `ser_2`: A `pd.Series` of length `3`, named `"SERIES_WITH_ZEROS"`, filled with zeros and with the following indices: `["VAL_1", "VAL_2", "VAL_3"]`.
3. `ser_3`: A `pd.Series` named `"SERIES_FROM_NP_ARRAY"`, with a **numpy array** containing any `5` alpha characters.
4. `ser_4`: A `pd.Series` named `"SERIES_FROM_PY_DICT"`, using a **python dictionary** with indices `"INDEX_1", "INDEX_2", "INDEX_3"` and respective values: `"VAL_A", "VAL_B", "VAL_C"`.
5. `ser_5`: A `pd.Series` named `"SERIES_FROM_DF_COL"` containing the values of a column `"Feature_2"` predefined `pd.DataFrame` defined in the code: `defined_df`, and change the first index to `"CHANGED_INDEX"`.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
**For `ser_1`:** Define a list with the mentioned values and use it as an object in `data` parameter of `pd.Series`. Don't forget about `name`.

**For `ser_2`:** Recall how a single value can be used for `data` parameter and guide the duplication of this value using `index` argument. Don't forget about `name`.

**For `ser_3`:** Define a list object containing 5 ANY alphabetic letters and convert to a numpy array using `np.array(...)` syntax for input to `pd.Series`. Don't forget to name the `pd.Series`.

**For `ser_4`:** Remember a key-value map structure and map each index and value between each other and use it as input to `pd.Series` constructor. You may also recall such a useful function as `zip()`. Name the `pd.Series` object as required.

**For `ser_5`:** Don't worry about `pd.DataFrame` - it is already defined. Recall how you can access a specific column from `pd.DataFrame` object and use it as input to `pd.Series` and name it accordingly. Also, after the instantiation of the `pd.Series` with the contents being the `defined_df` first column - use `rename(index=...)` function to rename first index with `"CHANGED_INDEX"`

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are stuck)</font></b></summary>
    
  **For `ser_1`:** Use `pd.Series(data=[10, 20, 30, 40, 50], name="SERIES_FROM_LIST")` or:
  ```py
  interm_list = [10, 20, 30, 40, 50]
  ser_name = "SERIES_FROM_LIST"
  ser_1: pd.Series = pd.Series(data=interm_list, name=ser_name)
  ```

  **For `ser_2`:** Use `pd.Series(data=0, index=["VAL_1", "VAL_2", "VAL_3"], name="SERIES_FROM_ZEROS")` or:
  ```py
  data_to_dupl = 0
  indices_list = ["VAL_1", "VAL_2", "VAL_3"]
  ser_name = "SERIES_FROM_ZEROS"
  ser_2: pd.Series = pd.Series(data=data_to_dupl, index=indices_list, name=ser_name)
  ```

  **For `ser_3`:** Use `pd.Series(data=np.array(["a", "z", "Y", "C", "a"]), name="SERIES_FROM_NP_ARRAY")` or:
  ```py
  interm_list = ["a", "z", "Y", "C", "a"]
  np_array = np.array(interm_list)
  ser_name = "SERIES_FROM_NP_ARRAY"
  ser_3: pd.Series = pd.Series(data=np_array, name=ser_name)
  ```

  **For `ser_4`:** Use `pd.Series(data=dict(zip(["INDEX_1", "INDEX_2", "INDEX_3"], ["VAL_A", "VAL_B", "VAL_C"])), name="SERIES_FROM_PY_DICT")` or:
  ```py
  interm_indices_list = ["INDEX_1", "INDEX_2", "INDEX_3"]
  interm_values_list = ["VAL_A", "VAL_B", "VAL_C"]
  index_value_map = dict(zip(interm_indices_list, interm_values_list))
  ser_name: str = "SERIES_FROM_PY_DICT"
  ser_4: pd.Series = pd.Series(data=index_value_map, name=ser_name)
  ```

  **For `ser_5`:** Use `pd.Series(data=defined_df["Feature_2"], name="SERIES_FROM_DF_COL").rename(index={0: "CHANGED_INDEX"})` or:
  ```py
  new_index_map = {0: "CHANGED_INDEX"}
  extracted_series_from_df = defined_df["Feature_2"]
  ser_name = "SERIES_FROM_DF_COL"
  ser_5: pd.Series = pd.Series(data=extracted_series_from_df, name=ser_name).rename(index=new_index_map)
  ```

  </details>

</details>

In [13]:
# GRADED FUNCTION: create_pandas_series
def create_pandas_series() -> tuple[pd.Series]:
    """Creates and returns 5 different pd.Series using various creation methods.

    Returns:
        tuple[pd.Series]: A tuple containing 5 `pd.Series` objects:
            - ser_1: pd.Series named "SERIES_FROM_LIST" using a list with the following values: [10, 20, 30, 40, 50].
            - ser_2: pd.Series of length 3, named "SERIES_WITH_ZEROS", filled with zeros and with the following indices: ["VAL_1", "VAL_2", "VAL_3"].
            - ser_3: pd.Series named "SERIES_FROM_NP_ARRAY", with a numpy array containing any 5 alpha characters.
            - ser_4: pd.Series named "SERIES_FROM_PY_DICT", with indices "INDEX_1", "INDEX_2", "INDEX_3" and respective values: "VAL_A", "VAL_B", "VAL_C".
            - ser_5: pd.Series named "SERIES_FROM_DF_COL" containing the values of a column "Feature_2" predefined pd.DataFrame defined in the code: defined_df, 
                     and change the first index to "CHANGED_INDEX".
    """
    
    # Defined pd.DataFrame object.
    defined_df: pd.DataFrame = pd.DataFrame(
        data=[
            ["A", "B", "C"],
            [1, 2, 3],
            [None, .2, "D"]
        ],
        columns=["Feature_1", "Feature_2", "Feature_3"]
    )
    
    ### START CODE HERE ###
    # You may add intermediary objects if required, but keep all your custom code inside this section.
    
    # Create a pd.Series named "SERIES_FROM_LIST" using a python list with the following values: [10, 20, 30, 40, 50].
    interm_list = [10, 20, 30, 40, 50]
    ser_name = "SERIES_FROM_LIST"
    
    ser_1: pd.Series = pd.Series(data=interm_list, name=ser_name)
    
    # Create a pd.Series of length 3, named "SERIES_WITH_ZEROS", filled with zeros and with the following indices: ["VAL_1", "VAL_2", "VAL_3"].
    data_to_dupl = 0
    indices_list = ["VAL_1", "VAL_2", "VAL_3"]
    ser_name = "SERIES_FROM_ZEROS"
    
    ser_2: pd.Series = pd.Series(data=data_to_dupl, index=indices_list, name=ser_name)
    
    # Create a pd.Series named "SERIES_FROM_NP_ARRAY", with a numpy array containing any 5 alpha characters.
    interm_list = ["a", "z", "Y", "C", "a"]
    np_array = np.array(interm_list)
    ser_name = "SERIES_FROM_NP_ARRAY"
    
    ser_3: pd.Series = pd.Series(data=np_array, name=ser_name)
    
    # Create a pd.Series named "SERIES_FROM_PY_DICT", using a python dictionary with indices "INDEX_1", "INDEX_2", "INDEX_3" and respective values: "VAL_A", "VAL_B", "VAL_C".
    interm_indices_list = ["INDEX_1", "INDEX_2", "INDEX_3"]
    interm_values_list = ["VAL_A", "VAL_B", "VAL_C"]
    index_value_map = dict(zip(interm_indices_list, interm_values_list))
    ser_name: str = "SERIES_FROM_PY_DICT"
    
    ser_4: pd.Series = pd.Series(data=index_value_map, name=ser_name)
    
    # Create a pd.Series named "SERIES_FROM_DF_COL" containing the values of a column `"Feature_2"` predefined pd.DataFrame defined in the code: defined_df, 
    #   and change the first index to "CHANGED_INDEX".
    new_index_map = {0: "CHANGED_INDEX"}
    extracted_series_from_df = defined_df["Feature_2"]
    ser_name = "SERIES_FROM_DF_COL"
    
    ser_5: pd.Series = pd.Series(data=extracted_series_from_df, name=ser_name).rename(index=new_index_map)
    
    ### END CODE HERE ###
    
    return ser_1, ser_2, ser_3, ser_4, ser_5

In [14]:
ser_1, ser_2, ser_3, ser_4, ser_5 = create_pandas_series()

In [15]:
# SERIES_FROM_LIST
ser_1

0    10
1    20
2    30
3    40
4    50
Name: SERIES_FROM_LIST, dtype: int64

In [16]:
# SERIES_WITH_ZEROS
ser_2

VAL_1    0
VAL_2    0
VAL_3    0
Name: SERIES_FROM_ZEROS, dtype: int64

In [17]:
# SERIES_FROM_NP_ARRAY
ser_3

0    a
1    z
2    Y
3    C
4    a
Name: SERIES_FROM_NP_ARRAY, dtype: str

In [18]:
# SERIES_FROM_PY_DICT
ser_4

INDEX_1    VAL_A
INDEX_2    VAL_B
INDEX_3    VAL_C
Name: SERIES_FROM_PY_DICT, dtype: str

In [19]:
# SERIES_FROM_DF_COL
ser_5

CHANGED_INDEX      B
1                  2
2                0.2
Name: SERIES_FROM_DF_COL, dtype: object

In [20]:
# Test your implementation
unittests.exercise_1(create_pandas_series)

 All tests passed!

<a name='12---dataframe'></a>
### 1.2 Introduction to `pd.DataFrame`
DataFrames are formed of the following key elements:

1. **Data** – The actual values stored in tabular form (rows and columns).
2. **Index** – The row labels that identify each row uniquely.
3. **Columns** – The column labels (names) that identify each variable/field.
4. **Dtypes** – The data types of each column (e.g., int, float, string, bool).

These structures can be instantiated in various ways:

1. From a dictionary of lists or arrays
2. From a list of dictionaries
3. From a NumPy array
4. From another DataFrame or Series
5. From external files (CSV, Excel, SQL, JSON, etc.) - will be covered further in the notebook.

In [21]:
# 1. Using a dictionary with values
# keys = column names
# values = values associated with a specific key/column
dict_of_data: dict[str, Any] = {
    "feature_1": [1.2, 2, 3],
    "feature_2": [3, 4.2, 5],
    "feature_3": [5, 5.3, 1.2]
}
df_from_dict: pd.DataFrame = pd.DataFrame(data=dict_of_data)
df_from_dict

   feature_1  feature_2  feature_3
0        1.2        3.0        5.0
1        2.0        4.2        5.3
2        3.0        5.0        1.2

In [22]:
# 2. Using a list of dictionaries
# Each key-value pair in the dictionaries represent a value associated with a column/key
list_of_dicts: list[dict] = [
    {"A": 1, "B": 4},
    {"A": 2, "B": 5},
    {"A": 3, "C": 3}
]
df_from_list: pd.DataFrame = pd.DataFrame(data=list_of_dicts)
df_from_list

   A    B    C
0  1  4.0  NaN
1  2  5.0  NaN
2  3  NaN  3.0

In [23]:
# 3. Using numpy arrays
# In this case, the contents of the numpy array are treated as values
# By default, it will use numbers for columns, unless you specify the actual names for columns
#   inside the argument for pd.DataFrame
np_array: np.ndarray = np.array([[1, 2, 3], [3, 4, 5]])

df_from_np_array = pd.DataFrame(data=np_array, columns=["A", "B", "C"])
df_from_np_array

   A  B  C
0  1  2  3
1  3  4  5

In [24]:
# 4.1 From another Dataframe (copy)
df_original = pd.DataFrame(
    data={
        "A": [1, 2, 3],
        "B": [4, 5, 6],
        "C": [7, 8, 9]
    }
)

df_copy = pd.DataFrame(data=df_original)
df_copy

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [25]:
# 4.2 From a subset from original DataFrame
df_subset = pd.DataFrame(data=df_original[["A", "B"]])
df_subset

   A  B
0  1  4
1  2  5
2  3  6

In [26]:
# 4.3 From Series
series = pd.Series(data=[10, 20, 30], name="C")

df_from_series = pd.DataFrame(data=series)
df_from_series

    C
0  10
1  20
2  30

In [27]:
# 4.4 From multiple Series as separate columns
series_1: pd.Series = pd.Series(data=[10, 20, 30], name="C")
series_2: pd.Series = pd.Series(data=["A", "B", "C"], name="D")
series_3: pd.Series = pd.Series(data=[4.3, "ABC", 3.211], name="E")

col_name_values_map: dict[str, pd.Series] = {
    # Use for column names Series name
    series_1.name: series_1,
    # Use custom name as column name
    "Another_Name": series_2,
    # or other data type
    3: series_3
}

df_from_series = pd.DataFrame(data=col_name_values_map)
df_from_series

    C Another_Name      3
0  10            A    4.3
1  20            B    ABC
2  30            C  3.211

<a name='exercise-2---create-pandas-dataframes'></a>
### **Exercise 2 - `create_pandas_dataframes`**

**Your Task:**

Implement the `create_pandas_dataframes` function that returns a tuple of 4 `pd.DataFrames` created using different methods:

1. `df_1`: A `pd.DataFrame` using a **python dictionary** with the following values: 
    * `[1, 2, 3]` values for column with the name: `"FEAT_3"`,
    * `[20, 50, 80]` values for column with the name: `"FEAT_2"`,
    * `[5, 10, 15]` values for column with the name: `"FEAT_3"`.
2. `df_2`: A `pd.DataFrame` using a **list of python dictionaries** with column names: `"FEAT_1", "FEAT_2", "FEAT_3"` and strictly `3` alpha characters as values per each feature.
3. `df_3`: A `pd.DataFrame` using a 2-dimensional **numpy array** with 4 columns and 3 rows of any values of `float` data type.
4. `df_4`: A `pd.DataFrame` using 4 `pd.Series` defined objects: `defined_ser_1`, `defined_ser_2`, `defined_ser_3` and `defined_ser_4`. Make sure to follow the instructions below:
    * For columns on odd positions - use the names of the `pd.Series` objects. 
    * For columns on even positions - rename the names of columns with new name: `"NEW_COL_NAME_{idx}"`, where `idx` is replaced with the position of the column.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
**For `df_1`:** Remember a key-value map structure and map each column name and column values between each other and use it as input to `pd.DataFrame` constructor.

**For `df_2`:** Per each row, create a dictionary in which the keys are the columns/feature names and the value per feature/column name is an alphabetic character, and place those dictionaries in the list that will be used as input to `pd.DataFrame` constructor.

**For `df_3`:** Define `3` list objects containing 4 ANY `float` values and use them to create a numpy array using `np.array([...])` syntax for input to `pd.DataFrame`.

**For `df_4`:** Create a dictionary in which odd-positioned keys are the names of the columns (extract from `pd.Series` using `name` attribute) and even-positioned keys are custom f-strings with generic `"NEW_COL_NAME_{idx}"` where `idx` is replaced with the index of the key. Recall dict comprehension technique and `enumerate(...)` function for easier implementation.

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are stuck)</font></b></summary>
    
  **For `df_1`:** Use the following code:
  ```py
  interm_dict = {
    "FEAT_1": [1, 2, 3],
    "FEAT_2": [20, 50, 80],
    "FEAT_3": [5, 10, 15]
  }
  df_1: pd.DataFrame = pd.DataFrame(data=interm_dict)
  ```

  **For `df_2`:** Use the following code:
  ```py
  interm_list_of_dicts: list[dict] = [
    {"FEAT_1": "a", "FEAT_2": "c", "FEAT_3": "d"},
    {"FEAT_1": "b", "FEAT_2": "f", "FEAT_3": "q"},
    {"FEAT_1": "s", "FEAT_2": "l", "FEAT_3": "z"},
  ]
  df_2: pd.DataFrame = pd.DataFrame(data=interm_list_of_dicts)
  ```

  **For `df_3`:** Use the following code:
  ```py
  interm_list_1 = [.2, .33, 5.1, 6.5]
  interm_list_2 = [1.111, .31, 63.1, .1]
  interm_list_3 = [.1, 2.1, 3.2, 10.8]
  interm_np_array = np.array([interm_list_1, interm_list_2, interm_list_3])
  df_3: pd.DataFrame = pd.DataFrame(data=interm_np_array)
  ```

  **For `df_4`:** Use the following code:
  ```py
  interm_list_of_series = [defined_ser_1, defined_ser_2, defined_ser_3, defined_ser_4]
  interm_dict = {f"NEW_COL_NAME_{idx + 1}" if idx % 2 == 0 else series_obj.name: series_obj.values for idx, series_obj in enumerate(interm_list_of_series, start=1)}
  df_4: pd.DataFrame = pd.DataFrame(data=interm_dict)
  ```

  </details>

</details>

In [28]:
# GRADED FUNCTION: create_pandas_dataframes
def create_pandas_dataframes() -> tuple[pd.DataFrame]:
    """Creates and returns 4 different pd.DataFrame using various creation methods.

    Returns:
        tuple[pd.DataFrame]: A tuple containing 5 `pd.DataFrame` objects:
            - df_1: A pd.DataFrame using a python dictionary with the following values:
                    - [1, 2, 3] values for column with the name: "FEAT_1",
                    - [20, 50, 80] values for column with the name: "FEAT_2",
                    - [5, 10, 15] values for column with the name: "FEAT_3".
            - df_2: A pd.DataFrame using a list of python dictionaries with column names: "FEAT_1", "FEAT_2", "FEAT_3" and any alpha 
                    character as values per each feature.
            - df_3: A pd.DataFrame using a 2-dimensional numpy array with 4 columns and 3 rows of any values of float64 data type.
            - df_4: A pd.DataFrame using 4 pd.Series defined objects: defined_ser_1, defined_ser_2, defined_ser_3 and defined_ser_4. Make sure to follow the instructions below:
                    - For columns on odd positions - use the names of the pd.Series objects. 
                    - For columns on even positions - rename the names of columns with new name: "NEW_COL_NAME_{idx}", where idx is replaced with the position of the column.
    """
    
    # Defined pd.Series objects.
    defined_ser_1: pd.Series = pd.Series(data=["A", "B", "C"], name="Feature_1")
    defined_ser_2: pd.Series = pd.Series(data=[1, 2, 3], name="Feature_2")
    defined_ser_3: pd.Series = pd.Series(data=[None, 4.3, None], name="Feature_3")
    defined_ser_4: pd.Series = pd.Series(data=["D", "S", None], name="Feature_3")
    
    ### START CODE HERE ###
    # You may add intermediary objects if required, but keep all your custom code inside this section.
    
    # Create a pd.DataFrame using a python dictionary with the following values: 
    #   - `[1, 2, 3]` values for column with the name: `"FEAT_1"`,
    #   - `[20, 50, 80]` values for column with the name: `"FEAT_2"`,
    #   - `[5, 10, 15]` values for column with the name: `"FEAT_3"`.
    interm_dict = {
        "FEAT_1": [1, 2, 3],
        "FEAT_2": [20, 50, 80],
        "FEAT_3": [5, 10, 15]
    }
    
    df_1: pd.DataFrame = pd.DataFrame(data=interm_dict)
    
    # Create a pd.DataFrame using a list of python dictionaries with column names: "FEAT_1", "FEAT_2", "FEAT_3" 
    #   and any alpha character as values per each feature.
    interm_list_of_dicts: list[dict] = [
        {"FEAT_1": "a", "FEAT_2": "c", "FEAT_3": "d"},
        {"FEAT_1": "b", "FEAT_2": "f", "FEAT_3": "q"},
        {"FEAT_1": "s", "FEAT_2": "l", "FEAT_3": "z"},
    ]
    
    df_2: pd.DataFrame = pd.DataFrame(data=interm_list_of_dicts)
    
    # Create a pd.DataFrame using a 2-dimensional numpy array with 4 columns and 3 rows of any values of float64 data type.
    interm_list_1 = [.2, .33, 5.1, 6.5]
    interm_list_2 = [1.111, .31, 63.1, .1]
    interm_list_3 = [.1, 2.1, 3.2, 10.8]
    interm_np_array = np.array([interm_list_1, interm_list_2, interm_list_3])
    
    df_3: pd.DataFrame = pd.DataFrame(data=interm_np_array)
    
    # Create a pd.DataFrame using 4 pd.Series defined objects: `defined_ser_1`, `defined_ser_2`, `defined_ser_3` and `defined_ser_4`. Make sure to follow the instructions below:
    #   - For columns on odd positions - use the names of the `pd.Series` objects. 
    #   - For columns on even positions - rename the names of columns with new name: `"NEW_COL_NAME_{idx}"`, where `idx` is replaced with the position of the column.
    interm_list_of_series = [defined_ser_1, defined_ser_2, defined_ser_3, defined_ser_4]
    interm_dict = {
        f"NEW_COL_NAME_{idx}" if idx % 2 == 0 else series_obj.name: series_obj.values for idx, series_obj in enumerate(interm_list_of_series, start=1)
    }
    
    df_4: pd.DataFrame = pd.DataFrame(data=interm_dict)
    
    ### END CODE HERE ###
    
    return df_1, df_2, df_3, df_4

In [29]:
df_1, df_2, df_3, df_4 = create_pandas_dataframes()

In [30]:
# DATAFRAME_FROM_LIST
df_1

   FEAT_1  FEAT_2  FEAT_3
0       1      20       5
1       2      50      10
2       3      80      15

In [31]:
# DATAFRAME_WITH_ZEROS
df_2

  FEAT_1 FEAT_2 FEAT_3
0      a      c      d
1      b      f      q
2      s      l      z

In [32]:
# DATAFRAME_FROM_NP_ARRAY
df_3

       0     1     2     3
0  0.200  0.33   5.1   6.5
1  1.111  0.31  63.1   0.1
2  0.100  2.10   3.2  10.8

In [33]:
# DATAFRAME_FROM_PY_DICT
df_4

  Feature_1  NEW_COL_NAME_2  Feature_3 NEW_COL_NAME_4
0         A               1        NaN              D
1         B               2        4.3              S
2         C               3        NaN            NaN

In [34]:
# Test your implementation
unittests.exercise_2(create_pandas_dataframes)

 All tests passed!

<a name='2---csv-files'></a>
## 2 - Loading from CSV file

One of the most common formats in public datasets used for Machine Learning applications you can find are `.csv` files. They are easy to deserealize into python objects using classical pythonic way - via opening the file and reading manually through each line, alongside with the column names, which are most of the time present in the file as well. However, this can be cumbersome and require deeper file read errors, manual null values handling and others. As it was mentioned, `pandas` library offer multiple functions to read from different file formats, including `.csv` files, with already working error handling, handling of null values and automatic transformation into a `pandas` data structures objects with their own useful methods, that will be covered in the next submodule exercises.

CSV, or Comma-Separated Values file format, with the extension `.csv` (e.g. `price_data.csv`), is a plain text data format for storing tabular data, with the benefits of being human-readable, easy-to-use, in which each row contains values separated by a character, most of the time - via commas - ",", which represents a convention, but is not strict, since the separator may vary in character, since CSV files are basically a variation of a [Delimiter-Separated Value](https://en.wikipedia.org/wiki/Delimiter-separated_values) format. Usually, the first row, representing the zero-index in the CSV file, contains the names for the fields/columns.

Below is presented an small example of a `.csv` file that you are going to use in further exercises. This represents a subset of Spotify Tracks and fields that are present in the dataset.
```csv
row_id,track_id,artists,album_name,track_name,popularity,duration_ms
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826
```

<a name='21---read-csv-files'></a>
### 2.1. Reading a `.csv` file using `pd.read_csv()`
The official documentation of this function signature and internal workings can be accessed via the official website ([AVAILABLE HERE](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)). Take a minute to access the link and read through the available function arguments and return type, as well as the official description. In short, the most used arguments are presented in the simplified function description below:
```py
# pandas lib code
def read_csv(filepath_or_buffer: FilePath, 
             sep: str = ",", 
             header: int | Sequence[int] | Literal["infer"] | None = "infer", 
             names: Sequence[Hashable],
             index_col: Hashable | Sequence[Hashable] | False = None,
             usecols: Sequence[Hashable] | Callable = None,
             nrows: int = None,
             skiprows: int = None
             ...) -> pd.DataFrame:
    """
    Read a comma-separated values (csv) file into DataFrame.

    ...

    Parameters:
        filepath_or_buffer (FilePath): Any valid string local path, valid remote URL pointing to a .csv file.
        sep (str): Character or regex pattern to treat as the delimiter of the values and fields. Defaults to ",".
                   Take into consideration that you should not always rely on conventional principles of using comma
                   as a delimiter, take a look into the file using appropriate external services - for example, 
                   any spreadsheet, and identify the actual delimiter used.
        header (int | Sequence[int] | Literal["infer"] | None): Row number(s) containing column labels and marking the start of 
                                                                the data (zero-indexed). Defaults to "infer" - automatically
                                                                identify the name of the columns.
        names (Sequence[Hashable]): Sequence of column labels to apply. If the file contains a header row, then you should 
                                    explicitly pass ``header=0`` to override the column names. In other words, by passing
                                    a sequence of names in here, they will be used instead of the ones present in the file
                                    for column names.
        index_col (Hashable | Sequence[Hashable] | False): Specify the name of the column to use as the Index column in the DataFrame.
                                                           Useful when in the dataset is already a column representing ID or any other
                                                           unit of row distinction.
        usecols (Sequence[Hashable] | Callable): Specify either the index of the columns to be used and retrieved in a pd.DataFrame
                                                  or the actual name of the columns.
        nrows (int): Number of rows to take from the .csv file. Especially helpful when dealing with large datasets. Defaults to None.
        skiprows (int | Sequence[int]): Number of rows to skip from the .csv file. Be cautious using this, since it may omit the column names that may
                                        be specified in one of the rows that are skipped. You may use range() and exclude column names row from skipped.
    ...
    """
```

We encourage you to access the whole documentation and range of arguments, as well as use cases, in order to better understand what each argument is responsible for. For simplicity and general use case, the above-mentioned ones are more than enough.

Let's try and read from the defined path to the local `.csv` file:

In [35]:
path_to_csv_file = helper_utils.get_path_to_dataset_by_type(dataset_type="csv")
print(f"Shortened path to the CSV dataset: {helper_utils.format_path_to_file(path=path_to_csv_file)}")

Shortened path to the CSV dataset: ../datasets/csv/dataset.csv

In [36]:
df: pd.DataFrame = pd.read_csv(filepath_or_buffer=path_to_csv_file,  # path to .csv file.
                               sep=",",  # values are separated by a comma.
                               header=0,  # use as column names the names at first row in the .csv file.
                               names=None,  # use original column names as in the .csv file.
                               index_col=0,  # use as Index column - the first column of the .csv file.
                               usecols=range(0, 10),  # extract first 10 columns.
                               nrows=15,  # extract first 15 rows from the .csv file.
                               skiprows=range(1, 51, 1)  # skip first 50 rows starting from row with index 1 from the .csv file.
                               )
df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy
50,72xTsTouZ5nBmASX8k1XCW,Highland Peak,Trampoline (Acoustic),Trampoline - Acoustic,46,213098,False,0.596,0.200
51,3ILmwMefYZoQh5Cf5jeuUQ,Motohiro Hata,Documentary,透明だった世界,61,232360,False,0.373,0.914
52,2DHDuADAHoUW6n0z80RLQF,Andrew Belle,Black Bear,Pieces,60,241119,False,0.494,0.652
53,5JDcQAztvZTIkrWoZihgvC,Ron Pope,The Bedroom Demos,A Drop in the Ocean,68,220239,False,0.447,0.393
54,2sYFi9xVSZ56WHKSY2fN1K,Adam Christopher,So Far Away (Acoustic),So Far Away - Acoustic,52,171543,False,0.576,0.331
55,6xJOhSm4SvZwzy3uhWz26O,Andrew Belle,Black Bear,The Enemy,62,286865,False,0.536,0.890
56,7lLKxcNeJtDTWVRKHovLEC,Aron Wright,Build It Better,Build It Better,51,234473,False,0.526,0.333
57,25UzeaV47eDT44Fovve6xQ,Chord Overstreet,Sleepwalking in the Rain,Sleepwalking in the Rain,0,216000,False,0.501,0.381
58,4oa14QBfWRDfJy2agySy0L,Sara Bareilles,Little Voice,Gravity,67,232760,False,0.270,0.275
59,2gRKq9rIC5i1zuxp06zJWH,Chord Overstreet,What's Left of You,What's Left of You,57,178600,True,0.731,0.507
60,08MFgEQeVLF37EyZ7jcwLc,Zack Tabudlo,Pano,Pano,75,254400,False,0.375,0.457
61,6nXIYClvJAfi6ujLiKqEq8,Andrew Belle,The Daylight EP,Sky's Still Blue,62,244320,False,0.430,0.791
62,7x4b0UccXSKBWxWmjcrG2T,Kurt Cobain,Montage Of Heck: The Home Recordings,And I Love Her,66,124933,False,0.616,0.282
63,6owKuyHxUqidcAA6fPKSyy,Boyce Avenue;Bea Miller,"Cover Sessions, Vol. 3",We Can't Stop,64,222146,False,0.705,0.347
64,0wbmIfvndFV9VDvuUY1pYN,Tim Halperin,Covers,Always Be My Baby,62,181852,False,0.582,0.255

As a pre-step to actually extracting the entire data from any file with data, you should look at the file directly - either programmatically or using other services/apps. When dealing with `.csv` files, you may extract only the first row (zero-indexed), which, usually, specifies the column names, and extract the names of the columns as a first exploration of the dataset. Later, when loading the entire dataset, you may use concrete names of the column if required. In case a column name is missing, `pandas` automatically names it in the following way: `"Unnamed: {idx}"`, where `idx` is the actual index of the column whose name is missing.

In [37]:
cols = pd.read_csv(filepath_or_buffer=path_to_csv_file, nrows=0).columns
for idx, col_name in enumerate(cols):
    print(f"Column index = {idx}: name = \"{col_name}\"")

Column index = 0: name = "Unnamed: 0"
Column index = 1: name = "track_id"
Column index = 2: name = "artists"
Column index = 3: name = "album_name"
Column index = 4: name = "track_name"
Column index = 5: name = "popularity"
Column index = 6: name = "duration_ms"
Column index = 7: name = "explicit"
Column index = 8: name = "danceability"
Column index = 9: name = "energy"
Column index = 10: name = "key"
Column index = 11: name = "loudness"
Column index = 12: name = "mode"
Column index = 13: name = "speechiness"
Column index = 14: name = "acousticness"
Column index = 15: name = "instrumentalness"
Column index = 16: name = "liveness"
Column index = 17: name = "valence"
Column index = 18: name = "tempo"
Column index = 19: name = "time_signature"
Column index = 20: name = "track_genre"

<a name='exercise-3---read-from-csv'></a>
### **Exercise 3 - `read_from_csv`**

**Your Task:**

Using `path_to_csv` path, implement the `read_from_csv` function that returns a tuple of 4 `pd.DataFrame` read from the same `.csv` file, but with the following conditions:

1. `df_from_csv_1`: A simple `pd.DataFrame` that contains the entire dataset from the `.csv` file as it is.
2. `df_from_csv_2`: A `pd.DataFrame` with first `10` non-header rows from the `.csv` file.
3. `df_from_csv_3`: A `pd.DataFrame` with last `6` columns with capitalized name and first `8` rows.
4. `df_from_csv_4`: A `pd.DataFrame` that stores first `5` rows, in which odd-indexed column names - are named using uppercase letters, and even-indexed ones - are the same as in the original file, skipping first `1000` rows, and using as index column - the column from the dataset under index `0`. 

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
**For `df_from_csv_1`:** Use only the defined path as the only argument in the `pandas` function that reads from csv file.

**For `df_from_csv_2`:** Take into consideration that, besides the zero-indexed row (which in this case is the `.csv` header - with column names), you are required to use `nrows` argument
                         with a unit/index in advance.

**For `df_from_csv_3`:** You may initially explore the column names and use them, since `pd.Index` object retains the order, but take into consideration that when reading again the `.csv` file, the column names are not capitalized - find a way to use the capitalized ones (recall `.rename()` method of `pd.DataFrame`), or use reverse range and figure out in the similar manner to change them. Former method will help with easier column names handling as required in the task. No one restricts you in using additional objects if required.

**For `df_from_csv_4`:** Similarily, as specified in the hint from `df_from_csv_3` sub-task, you may use the actual column names for the `usecols` parameter. Besides that, use `index` parameter to properly select the actual column to use as row indices object. Take into consideration that you may change `pd.DataFrame` columns - which are stored in the attribute `columns` - by assigning new values to it.

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>
    
  **For `df_from_csv_1`:** Use the following code:
  ```py
  df_from_csv_1: pd.DataFrame = pd.read_csv(filepath_or_buffer=path_to_csv)
  ```

  **For `df_from_csv_2`:** Use the following code:
  ```py
  df_from_csv_2: pd.DataFrame = pd.read_csv(filepath_or_buffer=path_to_csv, header=0, nrows=10)
  ```

  **For `df_from_csv_3`:** Use the following code:
  ```py
  col_names = pd.read_csv(path_to_csv, nrows=0).columns
  subset_col_names = col_names[-5:]
  df_from_csv_3: pd.DataFrame = pd.read_csv(path_to_csv, usecols=subset_col_names, nrows=8).rename(columns=str.capitalize)
  ```

  **For `df_from_csv_4`:** Use the following code:
  ```py
  col_names = pd.read_csv(path_to_csv, nrows=0).columns
  df_from_csv_4: pd.DataFrame = pd.read_csv(
      filepath_or_buffer=path_to_csv,
      index_col=0,
      skiprows=range(1, 1001),
      nrows=5,
  )
  new_cols = [
      col.upper() if (i + 1) % 2 == 1 else col
      for i, col in enumerate(df_from_csv_4.columns)
  ]
  df_from_csv_4.columns = new_cols
  ```

  </details>

</details>

In [38]:
# GRADED FUNCTION: read_from_csv
def read_from_csv() -> tuple[pd.DataFrame]:
    """Creates and returns 4 different pd.DataFrame using various arguments combinations from `pd.read_csv()` function.

    Returns:
        tuple[pd.DataFrame]: A tuple containing 4 pd.DataFrame objects:
            - df_from_csv_1: A pd.DataFrame from the .csv file, that:
                - contains the entire dataset from the .csv file as it is.
            - df_from_csv_2: A pd.DataFrame from the .csv file, with:
                - first 10 non-header rows.
            - df_from_csv_3: Create a pd.DataFrame from .csv file at path_to_csv, with:
                - only last 6 columns,
                - first 8 rows.
                - capitalize the columns,
            - df_from_csv_4: A pd.DataFrame from .csv file at path_to_csv, that:
                - stores first 5 non-header rows,
                - odd-indexed column names - are named using uppercase letters, 
                - even-indexed ones - are the same as in the original file, 
                - skipping first 1000 rows, 
                - using as index column - the column from the dataset under index 0. 
    """
    
    # Defined path to csv file.
    path_to_csv = helper_utils.get_path_to_dataset_by_type(dataset_type="csv")
    
    ### START CODE HERE ###
    # You may, and we encourage you to, add intermediary objects if required, but keep all your custom code inside this section.
    
    # Create a simple `pd.DataFrame` from the `.csv` file, that:
    #   - contains the entire dataset from the `.csv` file as it is.
    df_from_csv_1: pd.DataFrame = pd.read_csv(filepath_or_buffer=path_to_csv)
    
    # Create a `pd.DataFrame` from the `.csv` file, with:
    #   - first `10` non-header rows.
    df_from_csv_2: pd.DataFrame = pd.read_csv(filepath_or_buffer=path_to_csv, header=0, nrows=10)
    
    # Create a `pd.DataFrame` from `.csv` file at `path_to_csv`, with:
    #   - last `6` columns with capitalized name
    #   - first `8` rows.
    col_names = pd.read_csv(path_to_csv, nrows=0).columns
    subset_col_names = col_names[-6:]

    df_from_csv_3: pd.DataFrame = (
        pd.read_csv(path_to_csv, usecols=subset_col_names, nrows=8)
        .rename(columns=str.capitalize)
    )
    
    # Create a `pd.DataFrame` from `.csv` file at `path_to_csv`, that: 
    #   - stores first `5` non-header rows,
    #   - odd-indexed column names - are named using uppercase letters, 
    #   - even-indexed ones - are the same as in the original file, 
    #   - skipping first `1000` rows, 
    #   - using as index column - the column from the dataset under index `0`. 
    col_names = pd.read_csv(path_to_csv, nrows=0).columns

    df_from_csv_4: pd.DataFrame = pd.read_csv(
        filepath_or_buffer=path_to_csv,
        index_col=0,
        skiprows=range(1, 1001),
        nrows=5,
    )

    new_cols = [
        col.upper() if i % 2 == 1 else col
        for i, col in enumerate(df_from_csv_4.columns)
    ]

    df_from_csv_4.columns = new_cols
    
    ### END CODE HERE ###
    
    return df_from_csv_1, df_from_csv_2, df_from_csv_3, df_from_csv_4

In [39]:
df_from_csv_1, df_from_csv_2, df_from_csv_3, df_from_csv_4 = read_from_csv()

In [40]:
# DATAFRAME_WHOLE
df_from_csv_1

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [41]:
# DATAFRAME_5_ROWS
df_from_csv_2

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
5,5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,0.4810,...,-8.807,1,0.1050,0.2890,0.000000,0.1890,0.6660,98.017,4,acoustic
6,6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.1470,...,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
7,7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,0.4440,...,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
8,8,0IktbUcnAGrvD03AWnz3Q8,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,74,189613,False,0.625,0.4140,...,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
9,9,7k9GuJYLp2AzqokyEdwEw2,Ross Copperman,Hunger,Hunger,56,205594,False,0.442,0.6320,...,-6.770,1,0.0295,0.4260,0.004190,0.0735,0.1960,78.899,4,acoustic

In [42]:
# DATAFRAME_LAST_5_CAP_COLS_8_ROWS
df_from_csv_3

   Instrumentalness  Liveness  Valence    Tempo  Time_signature Track_genre
0          0.000001    0.3580   0.7150   87.917               4    acoustic
1          0.000006    0.1010   0.2670   77.489               4    acoustic
2          0.000000    0.1170   0.1200   76.332               4    acoustic
3          0.000071    0.1320   0.1430  181.740               3    acoustic
4          0.000000    0.0829   0.1670  119.949               4    acoustic
5          0.000000    0.1890   0.6660   98.017               4    acoustic
6          0.000003    0.0913   0.0765  141.284               3    acoustic
7          0.000000    0.0973   0.7120  150.960               4    acoustic

In [43]:
# DATAFRAME_UPP_ORIG_COLS_SKIP_1000_IDX_COL
df_from_csv_4

,track_id,ARTISTS,album_name,TRACK_NAME,popularity,DURATION_MS,explicit,DANCEABILITY,energy,KEY,loudness,MODE,speechiness,ACOUSTICNESS,instrumentalness,LIVENESS,valence,TEMPO,time_signature,TRACK_GENRE
1000,4pR4oQJULf7FDB54TleMyH,Limoblaze;Lecrae;Happi,Jireh (My Provider),Jireh (My Provider),64,168000,False,0.443,0.778,0,-7.564,0,0.2660,0.241,0.000000,0.2150,0.628,128.250,5,afrobeat
1001,4Ds4bq6aqOSAp1T7DikOi4,Criolo,Ainda Há Tempo,Ainda Há Tempo,44,318360,False,0.580,0.800,6,-7.528,1,0.3450,0.281,0.000000,0.0708,0.483,81.303,4,afrobeat
1002,7nYbKsvhM88mHCmFsAIQVp,Criolo,Fellini,Fellini,42,171989,False,0.805,0.746,1,-5.211,0,0.1850,0.238,0.000000,0.2150,0.717,127.922,4,afrobeat
1003,7gVNP7rI9UBZndge0ulKfL,Criolo,Nó na Orelha,Lion Man,46,205440,False,0.582,0.660,7,-4.988,0,0.0544,0.399,0.000000,0.1270,0.484,83.789,4,afrobeat
1004,1hLvWelTny8vttEEZIXVjw,Criolo,Espiral de Ilusão,Espiral de Ilusão,44,220800,False,0.776,0.314,2,-9.513,1,0.0340,0.881,0.000723,0.1390,0.476,124.055,4,afrobeat

In [44]:
# Test your implementation
unittests.exercise_3(read_from_csv)

 All tests passed!

<a name='3---excel-files'></a>
## 3 - Loading from Excel file

Another common format of public datasets used for ML applications you can find are `.xls` and `.xlsx` files or, simply, Excel files. They are usually created and edited using spreadsheet software (e.g., Microsoft Excel, Google Spreadsheets, etc.). Unlike plain text formats (e.g., `.csv`), Excel files can contain multiple worksheets within a single file, allowing datasets to be organized across different tabs. Excel datasets support rich features, such as: cell formatting, formulas, charts and merged cells, which can be useful for data analysis and presentation. However, these additional features also make Excel files less lightweight and less human-readable compared to `.csv` files.

They are harder to deserealize into python objects due to high variety of serialization formats that can be used:
1. `.xlsx` - XML format
2. `.xlsb` - Binary format
3. `.xlsm` - Macro-enabled
4. `.ods` - open-source standardized file format similar to Microsoft Excel format (e.g., used in LibreOffice)
4. and even in `.csv` format

All these taken into consideration, make Excel files harder to operate with and load into python objects. There are multiple libraries that do that, such as: `pandas` - with `pd.read_excel()` function, loading the contents of the Excel file directly into `pd.DataFrame` (with which you are familiar already), `openpyxl` - that is used for reading `.xlsx`/`.xlsm` files, `xlrd` - for reading legacy Excel files `.xls`, `pyxlsb` - used for reading binary Excel files `.xlsb` and other. Under the hood, `pandas` uses all the libraries mentioned previously, as well as others, to handle different types of Excel files.

Below is presented an small example of a `.xlsx` file that you are going to use in further exercises. This represents a subset of Avocado Prices dataset, alongside with the fields that are present in it.

| Unnamed: 0 | Date       | AveragePrice | Total Volume | 4046    | 4225    | 4770  | Total Bags | Small Bags | Large Bags | XLarge Bags | type         | year | region |
|-----------:|:----------:|:------------:|:------------:|:-------:|:-------:|:-----:|:----------:|:----------:|:----------:|:-----------:|:------------:|:----:|:------:|
| 0          | 2015-12-27 | 1.33         | 64236.6      | 1036.74 | 54454.8 | 48.16 | 8696.87    | 8603.62    | 93.25      | 0           | conventional | 2015 | Albany |
| 1          | 2015-12-20 | 1.35         | 54877        | 674.28  | 44638.8 | 58.33 | 9505.56    | 9408.07    | 97.49      | 0           | conventional | 2015 | Albany |
| 2          | 2015-12-13 | 0.93         | 118220       | 794.7   | 109150  | 130.5 | 8145.35    | 8042.21    | 103.14     | 0           | conventional | 2015 | Albany |
| 3          | 2015-12-06 | 1.08         | 78992.1      | 1132    | 71976.4 | 72.58 | 5811.16    | 5677.4     | 133.76     | 0           | conventional | 2015 | Albany |
| 4          | 2015-11-29 | 1.28         | 51039.6      | 941.48  | 43838.4 | 75.78 | 6183.95    | 5986.26    | 197.69     | 0           | conventional | 2015 | Albany |

<a name='31---read-excel-files'></a>
### 3.1. Reading a `.xlsx` file using `pd.read_excel()`
The official documentation of this function signature and internal workings can be accessed via the official website ([AVAILABLE HERE](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)). Take a minute to access the link and read through the available function arguments and return type, as well as the official description. In short, the most used arguments are presented in the simplified function description below:
```py
# pandas lib code
def read_excel(io: str | FilePath | ExcelFile, 
               sheet_name: str | int | list = 0, 
               header: int | list[int] = 0, 
               names: list = None,
               index_col: int | str | list[int] = None,
               usecols: str | list | Sequence | Callable = None,
               nrows: int = None,
               skiprows: int = None
               ...) -> pd.DataFrame:
    """
    Read an Excel file into a DataFrame. Supports xls, xlsx, xlsm, xlsb, odf, ods and odt file extensions and multiple worksheets.

    ...

    Parameters:
        io (str | FilePath | ExcelFile): Any valid string local path, valid remote URL pointing to an Excel file.
        sheet_name (str | int | list): Strings are used for sheet names. Integers are used in zero-indexed sheet positions 
                                       (chart sheets do not count as a sheet position). Lists of strings/integers are used 
                                       to request multiple sheets. When None, will return a dictionary containing DataFrames 
                                       for each sheet.
        header (int | list[int]): Row (0-indexed) to use for the column labels of the parsed DataFrame. If a list of 
                                  integers is passed those row positions will be combined into a MultiIndex. Use None 
                                  if there is no header.
        names (list): Sequence of column labels to apply. If the file does not contain a header row, then you should 
                      explicitly pass `header=None` to override the column names. In other words, by passing
                      a sequence of names in here, they will be used instead of the ones present in the file
                      for column names.
        index_col (Hashable | Sequence[Hashable] | False): Column (0-indexed) to use as the row labels of the DataFrame. 
                                                           Pass None if there is no such column. If a list is passed, those 
                                                           columns will be combined into a MultiIndex. If a subset of data 
                                                           is selected with usecols, index_col is based on the subset.
        usecols (str | list | Sequence | Callable): If None, then parse all columns.
                                                    If str, then indicates comma separated list of Excel column letters and column ranges 
                                                        (e.g. “A:E” or “A,C,E:F”). Ranges are inclusive of both sides.
                                                    If list of int, then indicates list of column numbers to be parsed (0-indexed).
                                                    If list of string, then indicates list of column names to be parsed.
                                                    If callable, then evaluate each column name against it and parse the column if the callable returns True.
        nrows (int): Number of rows to take from the excel file. Especially helpful when dealing with large datasets. Does not include header rows. Defaults to None.
        skiprows (int | Sequence[int]): Number of rows to skip from the excel file. Be cautious using this, since it may omit the column names that may
                                        be specified in one of the rows that are skipped. You may use range() and exclude column names row from skipped.
    ...
    """
```

We encourage you to access the whole documentation and range of arguments, as well as use cases, in order to better understand what each argument is responsible for. For simplicity and general use case, the above-mentioned ones are more than enough.

Let's try and read from the defined path to the local `.xlsx` file:

In [45]:
path_to_excel_file = helper_utils.get_path_to_dataset_by_type(dataset_type="excel")
print(f"Shortened path to the EXCEL dataset: {helper_utils.format_path_to_file(path=path_to_excel_file)}")

Shortened path to the EXCEL dataset: ../datasets/excel/avocado.xlsx

In [46]:
df: pd.DataFrame = pd.read_excel(io=path_to_excel_file,  # path to .xlsx file.
                                 sheet_name=0,  # extract all sheets in separate DataFrames
                                 header=0,  # use as column names the names at first row in the .csv file.
                                 names=None,  # use original column names as in the .csv file.
                                 index_col=0,  # use as Index column - the first column of the .csv file.
                                 usecols=range(0, 6),  # extract first 5 columns.
                                 nrows=15,  # extract first 15 rows from the .csv file.
                                 skiprows=range(1, 21, 1)  # skip first 20 rows starting from row with index 1 from the .csv file.
                                )
df

          Date  AveragePrice  Total Volume     4046       4225
20  2015-08-09          1.12     111140.93   584.63  100961.46
21  2015-08-02          1.45      75133.10   509.94   62035.06
22  2015-07-26          1.11     106757.10   648.75   91949.05
23  2015-07-19          1.26      96617.00  1042.10   82049.40
24  2015-07-12          1.05     124055.31   672.25   94693.52
25  2015-07-05          1.35     109252.12   869.45   72600.55
26  2015-06-28          1.37      89534.81   664.23   57545.79
27  2015-06-21          1.27     104849.39   804.01   76688.55
28  2015-06-14          1.32      89631.30   850.58   55400.94
29  2015-06-07          1.07     122743.06   656.71   99220.82
30  2015-05-31          1.23      95123.62   922.37   70469.69
31  2015-05-24          1.19     101470.91   680.27   71376.81
32  2015-05-17          1.43     109857.47  1150.55   81955.16
33  2015-05-10          1.26     120427.91  1420.43  102000.52
34  2015-05-03          1.20      59197.67   919.87   45490.05

When dealing with Excel files, you may extract only the first row (zero-indexed), which specifies the column names, and extract the names of the columns as a first exploration of the dataset. Later, when loading the entire dataset, you may use concrete names of the column if required. In case a column name is missing, `pandas` automatically names it in the following way: `"Unnamed: {idx}"`, where `idx` is the actual index of the column whose name is missing.

In [47]:
cols = pd.read_excel(io=path_to_excel_file, nrows=0).columns
for idx, col_name in enumerate(cols):
    print(f"Column index = {idx}: name = \"{col_name}\"")

Column index = 0: name = "Unnamed: 0"
Column index = 1: name = "Date"
Column index = 2: name = "AveragePrice"
Column index = 3: name = "Total Volume"
Column index = 4: name = "4046"
Column index = 5: name = "4225"
Column index = 6: name = "4770"
Column index = 7: name = "Total Bags"
Column index = 8: name = "Small Bags"
Column index = 9: name = "Large Bags"
Column index = 10: name = "XLarge Bags"
Column index = 11: name = "type"
Column index = 12: name = "year"
Column index = 13: name = "region"

Besides that, if you are using Visual Studio Code, you may use [Data Wrangler](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.datawrangler) extension in order to visualize datasets (not only Excel files, but also CSV, JSONL and other file formats as well). It is a useful utility tool that can visualize data inside datasets, provide means to interact with it and displays commonly used functions. Also, it uses `pandas` under the hood and enables Jupyter Notebooks to interact with the data inside. It can also generate from the code you wrote in this tool, separate notebooks. We highly suggest looking into it, however it is not mandatory to pass this module.

<a name='exercise-4---read-from-excel'></a>
### **Exercise 4 - `read_from_excel`**

**Your Task:**

Using `path_to_excel` path, implement the `read_from_excel` function that returns a tuple of 4 `pd.DataFrame` read from the same `.xlsx` file, but with the following conditions:

1. `df_from_excel_1`: A simple `pd.DataFrame` that contains the entire dataset from the `.xlsx` file as it is.
2. `df_from_excel_2`: A `pd.DataFrame` with last `15` non-header rows from the `.xlsx` file. Analyze `pd.DataFrame` methods for this assignment - you may use `.tail()` for this.
3. `df_from_excel_3`: A `pd.DataFrame` with first `5` rows and first `3` columns, renamed into custom names - `"Feat_{idx + 1}"` , where `idx` is the index of the feature in the original dataset.
4. `df_from_excel_4`: A `pd.DataFrame` that stores `10` rows, using as index column - the column from the dataset under index `0` and first `50` rows are omitted. Rename all columns into `"Feat_{idx + 1}"`, where `idx` is the index of the feature in the original dataset.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
**For `df_from_excel_1`:** Use only the defined path as the only argument in the `pandas` function that reads from Excel file.

**For `df_from_excel_2`:** Take into consideration that the zero-indexed row (which in this case is the `.xlsx` header - with column names), is at the beginning of the file, while `pd.DataFrame` should include also the last `15` rows. It can be done easily using `.tail(n=n)` method of `pd.DataFrame` and `pd.Series` classes - `n` specifies the number of rows to take.

**For `df_from_excel_3`:** You may initially explore the column names and use them, since `pd.Index` object retains the order, but take into consideration that when reading again the `.xlsx` file, the column names are the same as in the file - find a way to rename them (recall `.rename()` method of `pd.DataFrame`).

**For `df_from_excel_4`:** Use `index` parameter to properly select the actual column to use as row indices object. Use `skiprows` parameter to skip some rows. Use `names` to use list of custom names instead of the original ones.

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>
    
  **For `df_from_excel_1`:** Use the following code:
  ```py
  df_from_excel_1: pd.DataFrame = pd.read_excel(io=path_to_excel)
  ```

  **For `df_from_excel_2`:** Use the following code:
  ```py
  df_from_excel_2: pd.DataFrame = pd.read_excel(io=path_to_excel, header=0).tail(n=15)
  ```

  **For `df_from_excel_3`:** Use the following code:
  ```py
  col_names = pd.read_excel(path_to_excel, nrows=0).columns
  subset_col_names = col_names[:3]
  df_from_excel_3 = pd.read_excel(io=path_to_excel, usecols=subset_col_names, nrows=5)
  df_from_excel_3.columns = [f"Feat_{i + 1}" for i in range(len(df_from_excel_3.columns))]
  ```

  **For `df_from_excel_4`:** Use the following code:
  ```py
  df_from_excel_4 = pd.read_excel(io=path_to_excel, skiprows=50, nrows=10, index_col=0)
  df_from_excel_4.columns = [f"Feat_{i + 1}" for i in range(len(df_from_excel_4.columns))]
  ```

  </details>

</details>

In [48]:
# GRADED FUNCTION: read_from_excel
def read_from_excel() -> tuple[pd.DataFrame]:
    """Creates and returns 4 different pd.DataFrame using various arguments combinations from `pd.read_excel()` function.

    Returns:
        tuple[pd.DataFrame]: A tuple containing 4 pd.DataFrame objects:
            - df_from_excel_1: A pd.DataFrame from the .xlsx file, that:
                - contains the entire dataset from the .xlsx file as it is.
            - df_from_excel_2: A pd.DataFrame from the .xlsx file, with:
                - last 15 non-header rows. Analyze `pd.DataFrame` methods for this assignment - you may use `.tail()` for this.
            - df_from_excel_3: Create a pd.DataFrame from .xlsx file at path_to_excel, with:
                - only first 3 columns,
                - first 5 rows,
                - renamed columns into "Feat_{idx + 1}", where "idx" is the index of the feature in the original dataset.
            - df_from_excel_4: A pd.DataFrame from .xlsx file at path_to_excel, that:
                - stores first 10 non-header rows,
                - skipping first 50 rows,
                - using as index column - the column from the dataset under index 0,
                - all columns are renamed into "Feat_{idx + 1}", where "idx" is the index of the feature in the original dataset.
    """
    
    # Defined path to csv file.
    path_to_excel = helper_utils.get_path_to_dataset_by_type(dataset_type="excel")
    
    ### START CODE HERE ###
    # You may, and we encourage you to, add intermediary objects if required, but keep all your custom code inside this section.
    
    # Create a simple `pd.DataFrame` from the `.xlsx` file, that:
    #   - contains the entire dataset from the `.xlsx` file as it is.
    df_from_excel_1: pd.DataFrame = pd.read_excel(io=path_to_excel)
    
    # Create a `pd.DataFrame` from the `.xlsx` file, with:
    #   - last `15` non-header rows. Analyze `pd.DataFrame` methods for this assignment - you may use `.tail()` for this.
    df_from_excel_2: pd.DataFrame = pd.read_excel(io=path_to_excel, header=0).tail(n=15)
    
    # Create a `pd.DataFrame` from `.xlsx` file at `path_to_excel`, with:
    #   - only first 3 columns,
    #   - first 5 rows,
    #   - renamed columns into "Feat_{idx + 1}", where "idx" is the index of the feature in the original dataset.
    col_names = pd.read_excel(path_to_excel, nrows=0).columns
    subset_col_names = col_names[:3]
    
    df_from_excel_3: pd.DataFrame = pd.read_excel(io=path_to_excel, usecols=subset_col_names, nrows=5)
    df_from_excel_3.columns = [f"Feat_{i + 1}" for i in range(len(df_from_excel_3.columns))]
    
    # Create a `pd.DataFrame` from `.xlsx` file at `path_to_excel`, that:
    #   - stores first `10` non-header rows,
    #   - skipping first 50 rows,
    #   - using as index column - the column from the dataset under index 0,
    #   - all columns are renamed into "Feat_{idx + 1}", where "idx" is the index of the feature in the original dataset.
    df_from_excel_4: pd.DataFrame = pd.read_excel(io=path_to_excel, skiprows=50, nrows=10, index_col=0)

    df_from_excel_4.columns = [f"Feat_{i + 1}" for i in range(len(df_from_excel_4.columns))]
    
    ### END CODE HERE ###
    
    return df_from_excel_1, df_from_excel_2, df_from_excel_3, df_from_excel_4

In [49]:
df_from_excel_1, df_from_excel_2, df_from_excel_3, df_from_excel_4 = read_from_excel()

In [50]:
# DATAFRAME_WHOLE
df_from_excel_1

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [51]:
# DATAFRAME_LAST_15_ROWS
df_from_excel_2

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
18234,9,2018-01-21,1.83,189317.99,27049.44,33561.32,439.47,128267.76,76091.99,51947.50,228.27,organic,2018,West
18235,10,2018-01-14,1.82,207999.67,33869.12,47435.14,433.52,126261.89,89115.78,37133.99,12.12,organic,2018,West
18236,11,2018-01-07,1.48,297190.60,34734.97,62967.74,157.77,199330.12,103761.55,95544.39,24.18,organic,2018,West
18237,0,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.00,organic,2018,WestTexNewMexico
18238,1,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.00,organic,2018,WestTexNewMexico
18239,2,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.00,organic,2018,WestTexNewMexico
18240,3,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.00,organic,2018,WestTexNewMexico
18241,4,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.00,organic,2018,WestTexNewMexico
18242,5,2018-02-18,1.56,17597.12,1892.05,1928.36,0.00,13776.71,13553.53,223.18,0.00,organic,2018,WestTexNewMexico
18243,6,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.00,organic,2018,WestTexNewMexico
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.00,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.00,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.00,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.00,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.00,organic,2018,WestTexNewMexico

In [52]:
# DATAFRAME_FIRST_3_RENAMED_COLS_5_ROWS
df_from_excel_3

   Feat_1      Feat_2  Feat_3
0       0  2015-12-27    1.33
1       1  2015-12-20    1.35
2       2  2015-12-13    0.93
3       3  2015-12-06    1.08
4       4  2015-11-29    1.28

Run the cell below, and look carefully at the Index column. Notice how, actually, unnamed column from the `.xlsx` file (zero-indexed one), is not actually representing the indices, but something else. It could be an error in data entries, a column with totally different purpose, and so on. That is why it is very useful to analyze carefully the data prior to loading.

In [53]:
# DATAFRAME_RENAMED_COLS_10_ROWS_SKIP_50
df_from_excel_4

,Feat_1,Feat_2,Feat_3,Feat_4,Feat_5,Feat_6,Feat_7,Feat_8,Feat_9,Feat_10,Feat_11,Feat_12,Feat_13
49,,,,,,,,,,,,,
50,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.00,conventional,2015,Albany
51,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.00,conventional,2015,Albany
0,2015-12-27,0.99,386100.49,292097.36,27350.92,297.90,66354.31,48605.95,17748.36,0.00,conventional,2015,Atlanta
1,2015-12-20,1.08,331377.53,251774.15,20702.45,103.06,58797.87,46930.26,11867.61,0.00,conventional,2015,Atlanta
2,2015-12-13,0.96,417772.47,324932.28,31019.08,275.80,61545.31,38903.57,22628.21,13.53,conventional,2015,Atlanta
3,2015-12-06,1.07,357636.82,283024.01,23740.85,181.92,50690.04,37032.67,13654.66,2.71,conventional,2015,Atlanta
4,2015-11-29,0.99,333280.79,250288.65,28889.63,307.83,53794.68,33031.72,20738.55,24.41,conventional,2015,Atlanta
5,2015-11-22,1.00,356414.57,269799.03,29732.30,501.16,56382.08,36992.30,19389.78,0.00,conventional,2015,Atlanta
6,2015-11-15,1.13,339860.68,263915.78,28442.45,455.97,47046.48,33656.42,13390.06,0.00,conventional,2015,Atlanta
7,2015-11-08,1.12,334041.60,250441.38,34483.33,488.24,48628.65,35662.93,12941.12,24.60,conventional,2015,Atlanta

In [54]:
# Test your implementation
unittests.exercise_4(read_from_excel)

 All tests passed!

<a name='4---json-files'></a>
## 4 - Loading from JSON file

Another common format for public datasets used in ML applications is **JSON** (JavaScript Object Notation) files. JSON is a lightweight, text-based format for representing structured data. It is widely used for data interchange between applications and APIs due to its human-readable syntax and ease of parsing by machines. Unlike tabular formats like `.csv` or spreadsheet formats like `.xlsx`, JSON files can represent hierarchical data, such as nested objects or arrays, making them very flexible for complex datasets.

JSON datasets are commonly structured as:
1. **Objects** - collections of key-value pairs enclosed in `{}`.
2. **Arrays** - ordered lists of values enclosed in `[]`.
3. **Nested structures** - objects or arrays can be nested inside other objects or arrays to represent relationships between data points.

Because JSON can represent deeply nested or irregular data, it can be slightly more challenging to flatten into standard tabular formats, but it provides a very flexible way to store and transport complex datasets.

Python provides multiple ways to work with JSON files:
- The built-in `json` module can be used to read - `json.load()` or write - `json.dump()` JSON objects. In both cases, classical `python` objects will be used - dictionaries, lists, etc.
- `pandas` provides the `pd.read_json()` function, which can load a JSON file or JSON-formatted string directly into a `pd.DataFrame`. Under the hood, `pandas` handles different orientations (records, columns, index) and can parse nested structures into flat tables.

Below is a small example of a JSON dataset representing a subset of Iris Dataset. Each entry is a JSON object with fields:

```json
[
    {
        "sepalLength": 5.1, 
        "sepalWidth": 3.5, 
        "petalLength": 1.4, 
        "petalWidth": 0.2, 
        "species": "setosa"
    },
    {
        "sepalLength": 4.9, 
        "sepalWidth": 3.0, 
        "petalLength": 1.4, 
        "petalWidth": 0.2, 
        "species": "setosa"
    },
  ...
]
```

<a name='41---read-json-files'></a>
### 4.1. Reading a `.json` file using `pd.read_json()`
The official documentation of this function signature and internal workings can be accessed via the official website ([AVAILABLE HERE](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)). Take a minute to access the link and read through the available function arguments and return type, as well as the official description. In short, the most used arguments are presented in the simplified function description below:

```py
# pandas lib code
def read_excel(path_or_buf: str | FilePath | ExcelFile, 
               sheet_name: str | int | list = 0, 
               header: int | list[int] = 0, 
               names: list = None,
               index_col: int | str | list[int] = None,
               usecols: str | list | Sequence | Callable = None,
               nrows: int = None,
               skiprows: int = None
               ...) -> pd.DataFrame:
    """
    Convert a JSON string to pandas object. This method reads JSON files or JSON-like data and converts them into pandas objects. It supports a variety of input formats, including line-delimited JSON, compressed files, and various data representations (table, records, index-based, etc.)

    ...

    Parameters:
        path_or_buf (str | FilePath | ExcelFile): Any valid string local path, valid remote URL pointing to an JSON file.
        orient (str): Indication of expected JSON string format. Compatible JSON strings can be produced by to_json() 
                      with a corresponding orient value. In other words, it specifies the format of how data is structured
                      inside the JSON file. The valid values are:
                      - 'split' : dict like {{index -> [index], columns -> [columns], data -> [values]}}
                      - 'records' : list like [{{column -> value}}, ... , {{column -> value}}]
                      - 'index' : dict like {{index -> {{column -> value}}}}
                      - 'columns' : dict like {{column -> {{index -> value}}}}
                      - 'values' : just the values array
                      - 'table' : dict like {{'schema': {{schema}}, 'data': {{data}}}}
        typ (Literal["frame", "series"]): The type of object to recover. Either pd.DataFrame or pd.Series.
        lines (bool): Read the file as a json object per line. Useful in cases when you have .jsonl (JSON Lines) file format - in which 
                      json objects are localized on separate lines and not indented and split across lines as in classical format.
        nrows (int): The number of lines from the line-delimited jsonfile (.jsonl) that has to be read.
                     This can only be passed if `lines=True`.
    ...
    """
```

We encourage you to access the whole documentation and range of arguments, as well as use cases, in order to better understand what each argument is responsible for. For simplicity and general use case, the above-mentioned ones are more than enough.

Let's try and read from the defined path to the local `.json` files:

In [55]:
all_json_paths_map: dict[str, Path] = helper_utils.create_additional_json_files()
for orient, path in all_json_paths_map.items():
    print(f"Orient type: {orient} - Path: {path}")

Orient type: records - Path: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\json\iris.json
Orient type: split - Path: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\json\iris_split.json
Orient type: index - Path: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\json\iris_index.json
Orient type: columns - Path: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\json\iris_columns.json
Orient type: lines - Path: e:\Programming\Projects\Sigmoid\Sigmoid_SLP\machine-learning\exercises\module_2\lesson_2_1_multi_format_data_loading\notebooks\datasets\json\iris_lines.jsonl

In [56]:
path_to_records_json_file = all_json_paths_map["records"]
print(f"Shortened path to the original JSON dataset (orient=\"record\"): {helper_utils.format_path_to_file(path=path_to_records_json_file)}")

Shortened path to the original JSON dataset (orient="record"): ../datasets/json/iris.json

#### **JSON File (orient="records") has the following contents:**

```json
[
  {"sepalLength": 5.1, "sepalWidth": 3.5, "petalLength": 1.4, "petalWidth": 0.2, "species": "setosa"},
  {"sepalLength": 4.9, "sepalWidth": 3.0, "petalLength": 1.4, "petalWidth": 0.2, "species": "setosa"},
  ...
  {"sepalLength": 4.7, "sepalWidth": 3.2, "petalLength": 1.3, "petalWidth": 0.2, "species": "setosa"},
  {"sepalLength": 4.6, "sepalWidth": 3.1, "petalLength": 1.5, "petalWidth": 0.2, "species": "setosa"},
]
```

In [57]:
df_records: pd.DataFrame = pd.read_json(path_or_buf=path_to_records_json_file,  # path to .json file.
                                        orient="records",  # data records format [{{column -> value}}, ... , {{column -> value}}].
                                        typ="frame",  # to a DataFrame.
                                        lines=False,  # is not a .jsonl file.
                                        nrows=None  # Take all lines.
                                        )
df_records

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [58]:
path_to_split_json_file = all_json_paths_map["split"]
print(f"Shortened path to the original JSON dataset (orient=\"split\"): {helper_utils.format_path_to_file(path=path_to_split_json_file)}")

Shortened path to the original JSON dataset (orient="split"): ../datasets/json/iris_split.json

#### **JSON File (orient="split") has the following contents:**

```json
{
  "columns":[
    "sepalLength",
    "sepalWidth",
    "petalLength",
    "petalWidth",
    "species"
  ],
  "index":[
    0,
    1,
    ...
    148,
    149
  ],
  "data":[
    [
      5.1,
      3.5,
      1.4,
      0.2,
      "setosa"
    ],
    [
      4.9,
      3.0,
      1.4,
      0.2,
      "setosa"
    ],
    ...
    [
      6.2,
      3.4,
      5.4,
      2.3,
      "virginica"
    ],
    [
      5.9,
      3.0,
      5.1,
      1.8,
      "virginica"
    ]
  ]
}
```

In [59]:
df_split: pd.DataFrame = pd.read_json(path_or_buf=path_to_split_json_file,  # path to .json file.
                                      orient="split",  # data split format {{index -> [index], columns -> [columns], data -> [values]}}.
                                      typ="frame",  # to a DataFrame.
                                      lines=False,  # is not a .jsonl file.
                                      nrows=None  # Take all lines.
                                      )
df_split

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [60]:
path_to_index_json_file = all_json_paths_map["index"]
print(f"Shortened path to the original JSON dataset (orient=\"index\"): {helper_utils.format_path_to_file(path=path_to_index_json_file)}")

Shortened path to the original JSON dataset (orient="index"): ../datasets/json/iris_index.json

#### **JSON File (orient="index") has the following contents:**

```json
{
  "0":{
    "sepalLength":5.1,
    "sepalWidth":3.5,
    "petalLength":1.4,
    "petalWidth":0.2,
    "species":"setosa"
  },
  "1":{
    "sepalLength":4.9,
    "sepalWidth":3.0,
    "petalLength":1.4,
    "petalWidth":0.2,
    "species":"setosa"
  },
  "2":{
    "sepalLength":4.7,
    "sepalWidth":3.2,
    "petalLength":1.3,
    "petalWidth":0.2,
    "species":"setosa"
  },
  ...
  "148":{
    "sepalLength":6.2,
    "sepalWidth":3.4,
    "petalLength":5.4,
    "petalWidth":2.3,
    "species":"virginica"
  },
  "149":{
    "sepalLength":5.9,
    "sepalWidth":3.0,
    "petalLength":5.1,
    "petalWidth":1.8,
    "species":"virginica"
  }
}
```

In [61]:
df_index: pd.DataFrame = pd.read_json(path_or_buf=path_to_index_json_file,  # path to .json file.
                                      orient="index",  # data index format {{index -> {{column -> value}}}}.
                                      typ="frame",  # to a DataFrame.
                                      lines=False,  # is not a .jsonl file.
                                      nrows=None  # Take all lines.
                                      )
df_index

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [62]:
path_to_columns_json_file = all_json_paths_map["columns"]
print(f"Shortened path to the original JSON dataset (orient=\"columns\"): {helper_utils.format_path_to_file(path=path_to_columns_json_file)}")

Shortened path to the original JSON dataset (orient="columns"): ../datasets/json/iris_columns.json

#### **JSON File (orient="columns") has the following contents:**

```json
{
  "sepalLength":{
    "0":5.1,
    "1":4.9,
    ...
    "148":6.2,
    "149":5.9
  },
  "sepalWidth":{
    "0":3.5,
    "1":3.0,
    ...
    "148":3.4,
    "149":3.0
  },
  "petalLength":{
    "0":1.4,
    "1":1.4,
    ...
    "148":5.4,
    "149":5.1
  },
  "petalWidth":{
    "0":0.2,
    "1":0.2,
    ...
    "148":2.3,
    "149":1.8
  },
  "species":{
    "0":"setosa",
    "1":"setosa",
    ...
    "148":"virginica",
    "149":"virginica"
  }
}
```

In [63]:
df_columns: pd.DataFrame = pd.read_json(path_or_buf=path_to_columns_json_file,  # path to .json file.
                                        orient="columns",  # data columns format {{column -> {{index -> value}}}}.
                                        typ="frame",  # to a DataFrame.
                                        lines=False,  # is not a .jsonl file.
                                        nrows=None  # Take all lines.
                                        )
df_columns

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [64]:
path_to_lines_json_file = all_json_paths_map["lines"]
print(f"Shortened path to the original JSON dataset (lines=True): {helper_utils.format_path_to_file(path=path_to_lines_json_file)}")

Shortened path to the original JSON dataset (lines=True): ../datasets/json/iris_lines.jsonl

#### **JSON File (lines=True) has the following contents**:

```json
{"sepalLength":5.1,"sepalWidth":3.5,"petalLength":1.4,"petalWidth":0.2,"species":"setosa"}
{"sepalLength":4.9,"sepalWidth":3.0,"petalLength":1.4,"petalWidth":0.2,"species":"setosa"}
...
{"sepalLength":6.2,"sepalWidth":3.4,"petalLength":5.4,"petalWidth":2.3,"species":"virginica"}
{"sepalLength":5.9,"sepalWidth":3.0,"petalLength":5.1,"petalWidth":1.8,"species":"virginica"}
```

In [65]:
df_lines: pd.DataFrame = pd.read_json(path_or_buf=path_to_lines_json_file,  # path to .jsonl file.
                                      orient="records",  # data records format [{{column -> value}}, ... , {{column -> value}}].
                                      typ="frame",  # to a DataFrame.
                                      lines=True,  # is a .jsonl file.
                                      nrows=None  # Take all lines.
                                      )
df_lines

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

<a name='exercise-5---read-from-json'></a>
### **Exercise 5 - `read_from_json`**

**Your Task:**

Using `path_to_json_{orient/lines}` paths, where `orient` may be one of defined parameter types, implement the `read_from_json` function that returns a tuple of 5 `pd.DataFrame` read from these `.json` or `.jsonl` files, but with the following conditions:

1. `df_from_json_1`: A `pd.DataFrame` read from defined path: `path_to_records_json`,
2. `df_from_json_2`: A `pd.DataFrame` read from defined path: `path_to_split_json`,
3. `df_from_json_3`: A `pd.DataFrame` read from defined path: `path_to_index_json`,
4. `df_from_json_4`: A `pd.DataFrame`, containing last 30 rows, read from defined path: `path_to_columns_json`,
5. `df_from_json_5`: A `pd.DataFrame` containing first 50 rows, read from defined path: `path_to_lines_json`.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
**For `df_from_json_1`:** Recall correct `orient` argument value.

**For `df_from_json_2`:** Recall correct `orient` argument value.

**For `df_from_json_3`:** Recall correct `orient` argument value.

**For `df_from_json_4`:** Recall correct `orient` argument value. After read, use built-in method of `pd.DataFrame` class that selects a subset of the `pd.DataFrame`.

**For `df_from_json_5`:** Recall `lines` argument and what value should it be assigned to specify that each row is a separate JSON entity.

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>
    
  **For `df_from_json_1`:** Use the following code:
  ```py
  df_from_json_1: pd.DataFrame = pd.read_json(path_or_buf=path_to_records_json, orient="records")
  ```

  **For `df_from_json_2`:** Use the following code:
  ```py
  df_from_json_2: pd.DataFrame = pd.read_json(path_or_buf=path_to_split_json, orient="split")
  ```

  **For `df_from_json_3`:** Use the following code:
  ```py
  df_from_json_3: pd.DataFrame = pd.read_json(path_or_buf=path_to_index_json, orient="index")
  ```

  **For `df_from_json_4`:** Use the following code:
  ```py
  df_from_json_4: pd.DataFrame = pd.read_json(path_or_buf=path_to_columns_json, orient="columns").tail(n=30)
  ```

  **For `df_from_json_5`:** Use the following code:
  ```py
  df_from_json_5: pd.DataFrame = pd.read_json(path_or_buf=path_to_lines_json, lines=True, nrows=50)
  ```

  </details>

</details>

In [66]:
# GRADED FUNCTION: read_from_json
def read_from_json() -> tuple[pd.DataFrame]:
    """Creates and returns 5 different pd.DataFrame using various arguments combinations from `pd.read_json()` function.

    Using `path_to_{orient_type/lines}_json` paths, where `orient_type` may be one of defined parameter types, implement the 
    `read_from_json` function that returns a tuple of 5 `pd.DataFrame` read from these `.json` or `.jsonl` files.
    
    Returns:
        tuple[pd.DataFrame]: A tuple containing 5 pd.DataFrame objects:
            - df_from_json_1: A `pd.DataFrame` read from defined path: `path_to_records_json`,
            - df_from_json_2: A `pd.DataFrame` read from defined path: `path_to_split_json`,
            - df_from_json_3: A `pd.DataFrame` read from defined path: `path_to_index_json`,
            - df_from_json_4: A `pd.DataFrame`, containing last 30 rows, read from defined path: `path_to_columns_json`,
            - df_from_json_5: A `pd.DataFrame`, containing first 50 rows, read from defined path: `path_to_lines_json`.
    """
    
    # Defined paths to json files.
    path_mapping = helper_utils.read_additional_json_files_paths()
    path_to_records_json = path_mapping["records"]
    path_to_split_json = path_mapping["split"]
    path_to_index_json = path_mapping["index"]
    path_to_columns_json = path_mapping["columns"]
    path_to_lines_json = path_mapping["lines"]
    
    ### START CODE HERE ###
    # You may, and we encourage you to, add intermediary objects if required, but keep all your custom code inside this section.
    
    # `pd.DataFrame` read from defined path: `path_to_records_json`
    df_from_json_1: pd.DataFrame = pd.read_json(path_or_buf=path_to_records_json, orient="records")
    
    # `pd.DataFrame` read from defined path: `path_to_split_json`
    df_from_json_2: pd.DataFrame = pd.read_json(path_or_buf=path_to_split_json, orient="split")
    
    # `pd.DataFrame` read from defined path: `path_to_index_json`
    df_from_json_3: pd.DataFrame = pd.read_json(path_or_buf=path_to_index_json, orient="index")
    
    # `pd.DataFrame`, containing last 30 rows, read from defined path: `path_to_columns_json`
    df_from_json_4: pd.DataFrame = pd.read_json(path_or_buf=path_to_columns_json, orient="columns").tail(n=30)
    
    # `pd.DataFrame` containing first 50 rows, read from defined path: `path_to_lines_json`
    df_from_json_5: pd.DataFrame = pd.read_json(path_or_buf=path_to_lines_json, lines=True, nrows=50)

    ### END CODE HERE ###
    
    return df_from_json_1, df_from_json_2, df_from_json_3, df_from_json_4, df_from_json_5

In [67]:
df_from_json_1, df_from_json_2, df_from_json_3, df_from_json_4, df_from_json_5 = read_from_json()

In [68]:
# DATAFRAME_FROM_JSON_1
df_from_json_1

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [69]:
# DATAFRAME_FROM_JSON_2
df_from_json_2

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [70]:
# DATAFRAME_FROM_JSON_3
df_from_json_3

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [71]:
# DATAFRAME_FROM_JSON_4
df_from_json_4

     sepalLength  sepalWidth  petalLength  petalWidth    species
120          6.9         3.2          5.7         2.3  virginica
121          5.6         2.8          4.9         2.0  virginica
122          7.7         2.8          6.7         2.0  virginica
123          6.3         2.7          4.9         1.8  virginica
124          6.7         3.3          5.7         2.1  virginica
125          7.2         3.2          6.0         1.8  virginica
126          6.2         2.8          4.8         1.8  virginica
127          6.1         3.0          4.9         1.8  virginica
128          6.4         2.8          5.6         2.1  virginica
129          7.2         3.0          5.8         1.6  virginica
130          7.4         2.8          6.1         1.9  virginica
131          7.9         3.8          6.4         2.0  virginica
132          6.4         2.8          5.6         2.2  virginica
133          6.3         2.8          5.1         1.5  virginica
134          6.1         2.6          5.6         1.4  virginica
135          7.7         3.0          6.1         2.3  virginica
136          6.3         3.4          5.6         2.4  virginica
137          6.4         3.1          5.5         1.8  virginica
138          6.0         3.0          4.8         1.8  virginica
139          6.9         3.1          5.4         2.1  virginica
140          6.7         3.1          5.6         2.4  virginica
141          6.9         3.1          5.1         2.3  virginica
142          5.8         2.7          5.1         1.9  virginica
143          6.8         3.2          5.9         2.3  virginica
144          6.7         3.3          5.7         2.5  virginica
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

In [72]:
# DATAFRAME_FROM_JSON_5
df_from_json_5

    sepalLength  sepalWidth  petalLength  petalWidth species
0           5.1         3.5          1.4         0.2  setosa
1           4.9         3.0          1.4         0.2  setosa
2           4.7         3.2          1.3         0.2  setosa
3           4.6         3.1          1.5         0.2  setosa
4           5.0         3.6          1.4         0.2  setosa
5           5.4         3.9          1.7         0.4  setosa
6           4.6         3.4          1.4         0.3  setosa
7           5.0         3.4          1.5         0.2  setosa
8           4.4         2.9          1.4         0.2  setosa
9           4.9         3.1          1.5         0.1  setosa
10          5.4         3.7          1.5         0.2  setosa
11          4.8         3.4          1.6         0.2  setosa
12          4.8         3.0          1.4         0.1  setosa
13          4.3         3.0          1.1         0.1  setosa
14          5.8         4.0          1.2         0.2  setosa
15          5.7         4.4          1.5         0.4  setosa
16          5.4         3.9          1.3         0.4  setosa
17          5.1         3.5          1.4         0.3  setosa
18          5.7         3.8          1.7         0.3  setosa
19          5.1         3.8          1.5         0.3  setosa
20          5.4         3.4          1.7         0.2  setosa
21          5.1         3.7          1.5         0.4  setosa
22          4.6         3.6          1.0         0.2  setosa
23          5.1         3.3          1.7         0.5  setosa
24          4.8         3.4          1.9         0.2  setosa
25          5.0         3.0          1.6         0.2  setosa
26          5.0         3.4          1.6         0.4  setosa
27          5.2         3.5          1.5         0.2  setosa
28          5.2         3.4          1.4         0.2  setosa
29          4.7         3.2          1.6         0.2  setosa
30          4.8         3.1          1.6         0.2  setosa
31          5.4         3.4          1.5         0.4  setosa
32          5.2         4.1          1.5         0.1  setosa
33          5.5         4.2          1.4         0.2  setosa
34          4.9         3.1          1.5         0.2  setosa
35          5.0         3.2          1.2         0.2  setosa
36          5.5         3.5          1.3         0.2  setosa
37          4.9         3.6          1.4         0.1  setosa
38          4.4         3.0          1.3         0.2  setosa
39          5.1         3.4          1.5         0.2  setosa
40          5.0         3.5          1.3         0.3  setosa
41          4.5         2.3          1.3         0.3  setosa
42          4.4         3.2          1.3         0.2  setosa
43          5.0         3.5          1.6         0.6  setosa
44          5.1         3.8          1.9         0.4  setosa
45          4.8         3.0          1.4         0.3  setosa
46          5.1         3.8          1.6         0.2  setosa
47          4.6         3.2          1.4         0.2  setosa
48          5.3         3.7          1.5         0.2  setosa
49          5.0         3.3          1.4         0.2  setosa

In [73]:
# Test your implementation
unittests.exercise_5(read_from_json)

 All tests passed!

<a name='5---sql-db'></a>
## 5 - Loading from SQL Database

Another widely used source of public datasets in ML and data analysis workflows are **SQL databases**. SQL (Structured Query Language) databases store data in a structured, tabular format consisting of rows and columns, organized into tables that can be related to each other through keys. Unlike flat files such as `.csv` or hierarchical formats like JSON, SQL databases are designed for efficient querying, filtering, aggregation, and joining of large volumes of structured data.

A SQL dataset is typically stored inside a **database**, which contains:
1. **Tables** – structured collections of rows and columns (similar to DataFrames).
2. **Schemas** – logical groupings of related tables and metadata.
3. **Relations** – links between tables defined using primary and foreign keys.
4. **Indexes** – data structures that speed up search and retrieval operations.

Because SQL databases enforce schemas and data types, they provide strong guarantees about data consistency and integrity. They are commonly used in production systems, analytics pipelines, and large-scale ML workflows where datasets are too large or dynamic to be stored as static files.

In SQL databases, data is queried using SQL statements such as:
```sql
SELECT sepal_length, sepal_width, species
FROM iris
WHERE species = 'setosa';
```
This query retrieves a subset of rows and columns, from a table named `iris`, that belong to target class `setosa`. Such queries allow efficient filtering and aggregation directly within the database engine before loading the results into Python.

Python provides several ways to interact with SQL datasets:

1. The built-in sqlite3 module can be used to execute SQL queries against SQLite databases.
2. Database-specific connectors (e.g., psycopg2 for PostgreSQL, mysql-connector for MySQL) allow communication with remote databases.
3. pandas provides high-level functions such as `pd.read_sql()`, `pd.read_sql_query()`, and `pd.read_sql_table()` to load SQL query results directly into a `pd.DataFrame`.

Below is a small conceptual example of a SQL table representing a subset of the Iris dataset:

| id  | sepal_length | sepal_width | petal_length | petal_width |  species  |
| :-: | :----------: | :---------: | :----------: | :---------: | :-------: |
|  1  |      5.1     |     3.5     |      1.4     |     0.2     |   setosa  |
|  2  |      4.9     |     3.0     |      1.4     |     0.2     |   setosa  |
|  3  |      6.2     |     3.4     |      5.4     |     2.3     | virginica |

Using `pd.read_sql()`, you can execute a SQL query and load the returned result set directly into a `pd.DataFrame`, combining the flexibility of SQL querying with the convenience of pandas data manipulation tools.

<a name='51---read-sql-db'></a>
### 5.1. Reading an SQL Database using `pd.read_sql()`
The official documentation of this function signature and internal workings can be accessed via the official website ([AVAILABLE HERE](https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html)). Take a minute to access the link and read through the available function arguments and return type, as well as the official description. In short, the most used arguments are presented in the simplified function description below:

```py
# pandas lib code
def read_sql(sql: str | SQLAlchemy Selectable, 
             con: ADBC Connection | SQLAlchemy connectable | str | sqlite3 connection, 
             index_col: list | tuple | dict = None, 
             columns: list = None,
             params: list | tuple | dict = None
             ...) -> pd.DataFrame:
    """
    Read SQL query or database table into a DataFrame.

    This function is a convenience wrapper around read_sql_table and read_sql_query (for backward compatibility). It will delegate to the specific function depending on the provided input. A SQL query will be routed to read_sql_query, while a database table name will be routed to read_sql_table.

    ...

    Parameters:
        sql (str | SQLAlchemy Selectable): SQL query to be executed or a table name.
        con (ADBC Connection | SQLAlchemy connectable | str | sqlite3 connection): ADBC provides high performance I/O with native type support, where available. 
                                                                                   Using SQLAlchemy makes it  possible to use any DB supported by that library. 
                                                                                   If a DBAPI2 object, only sqlite3 is supported. The user is responsible for 
                                                                                   engine disposal and connection closure for the ADBC connection and SQLAlchemy 
                                                                                   connectable; str connections are closed automatically
        index_col (str | list[str]): Column(s) to set as index(MultiIndex).
        columns (list): List of column names to select from SQL table (only used when reading a table).
        params (list | tuple | dict): List of parameters to pass to execute method. The syntax used to pass parameters 
                                      is database driver dependent. Check database driver documentation for which of the 
                                      five syntax styles, described in PEP 249’s paramstyle, is supported. Eg. for psycopg2, 
                                      uses %(name)s so use params={‘name’ : ‘value’}. Basically, this can be reduced to SQL
                                      Queries that require some variable parameters.
    ...
    """
```

We encourage you to access the whole documentation and range of arguments, as well as use cases, in order to better understand what each argument is responsible for. For simplicity and general use case, the above-mentioned ones are more than enough.

Let's try and read from the defined path to the local SQLite Database:

In [74]:
path_to_sql_db_file = helper_utils.get_path_to_dataset_by_type(dataset_type="sql_db")
print(f"Shortened path to the SQLite dataset: {helper_utils.format_path_to_file(path=path_to_sql_db_file)}")

Shortened path to the SQLite dataset: ../datasets/sql_db/sql_sample_db

In [75]:
connection_sqlite = helper_utils.create_sqlite_conn(db_path=path_to_sql_db_file)

In [76]:
df: pd.DataFrame = pd.read_sql(sql="SELECT * FROM IRIS_DATASET_TABLE",  # name/query to perform.
                               con=connection_sqlite,  # using Connection to an SQL Database.
                               index_col=["id"],  # use as Index column - the first column of the resulting pd.DataFrame.
                               columns=None,  # use all columns.
                               params=None,  # Non-Parametrized SQL Query.
                               )
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
id
1            5.1         3.5          1.4         0.2     setosa
2            4.9         3.0          1.4         0.2     setosa
3            4.7         3.2          1.3         0.2     setosa
4            4.6         3.1          1.5         0.2     setosa
5            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
146          6.7         3.0          5.2         2.3  virginica
147          6.3         2.5          5.0         1.9  virginica
148          6.5         3.0          5.2         2.0  virginica
149          6.2         3.4          5.4         2.3  virginica
150          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [77]:
df: pd.DataFrame = pd.read_sql(sql="SELECT * FROM IRIS_DATASET_TABLE WHERE species = :species",  # name/parametrize query to perform.
                               con=connection_sqlite,  # using Connection to an SQL Database.
                               index_col=["id"],  # use as Index column - the first column of the resulting pd.DataFrame.
                               columns=None,  # use all columns.
                               params={"species": "setosa"},  # Parametrized SQL Query - selection of rows where species == setosa.
                               )
df

    sepalLength  sepalWidth  petalLength  petalWidth species
id
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa
6           5.4         3.9          1.7         0.4  setosa
7           4.6         3.4          1.4         0.3  setosa
8           5.0         3.4          1.5         0.2  setosa
9           4.4         2.9          1.4         0.2  setosa
10          4.9         3.1          1.5         0.1  setosa
11          5.4         3.7          1.5         0.2  setosa
12          4.8         3.4          1.6         0.2  setosa
13          4.8         3.0          1.4         0.1  setosa
14          4.3         3.0          1.1         0.1  setosa
15          5.8         4.0          1.2         0.2  setosa
16          5.7         4.4          1.5         0.4  setosa
17          5.4         3.9          1.3         0.4  setosa
18          5.1         3.5          1.4         0.3  setosa
19          5.7         3.8          1.7         0.3  setosa
20          5.1         3.8          1.5         0.3  setosa
21          5.4         3.4          1.7         0.2  setosa
22          5.1         3.7          1.5         0.4  setosa
23          4.6         3.6          1.0         0.2  setosa
24          5.1         3.3          1.7         0.5  setosa
25          4.8         3.4          1.9         0.2  setosa
26          5.0         3.0          1.6         0.2  setosa
27          5.0         3.4          1.6         0.4  setosa
28          5.2         3.5          1.5         0.2  setosa
29          5.2         3.4          1.4         0.2  setosa
30          4.7         3.2          1.6         0.2  setosa
31          4.8         3.1          1.6         0.2  setosa
32          5.4         3.4          1.5         0.4  setosa
33          5.2         4.1          1.5         0.1  setosa
34          5.5         4.2          1.4         0.2  setosa
35          4.9         3.1          1.5         0.2  setosa
36          5.0         3.2          1.2         0.2  setosa
37          5.5         3.5          1.3         0.2  setosa
38          4.9         3.6          1.4         0.1  setosa
39          4.4         3.0          1.3         0.2  setosa
40          5.1         3.4          1.5         0.2  setosa
41          5.0         3.5          1.3         0.3  setosa
42          4.5         2.3          1.3         0.3  setosa
43          4.4         3.2          1.3         0.2  setosa
44          5.0         3.5          1.6         0.6  setosa
45          5.1         3.8          1.9         0.4  setosa
46          4.8         3.0          1.4         0.3  setosa
47          5.1         3.8          1.6         0.2  setosa
48          4.6         3.2          1.4         0.2  setosa
49          5.3         3.7          1.5         0.2  setosa
50          5.0         3.3          1.4         0.2  setosa

It is also possible to extract column names, using SQL queries and SQL DB Connection Drivers. For the sake of simplicity, since this is out of scope of this course, you may research different ways to do that in dependence with the DB you have and other individual factors.

In [78]:
helper_utils.get_col_names_from_table(conn=connection_sqlite, table_name="IRIS_DATASET_TABLE")

[(0, 'id', 'INTEGER', 0, None, 1),
 (1, 'sepalLength', 'REAL', 0, None, 0),
 (2, 'sepalWidth', 'REAL', 0, None, 0),
 (3, 'petalLength', 'REAL', 0, None, 0),
 (4, 'petalWidth', 'REAL', 0, None, 0),
 (5, 'species', 'TEXT', 0, None, 0)]

In [79]:
helper_utils.close_sqlite_conn(conn=connection_sqlite)

<a name='exercise-6---read-from-sql-db'></a>
### **Exercise 6 - `read_from_sql_db`**

**Your Task:**

Using predefined path to SQLite DB file `path_to_sqlite_db_file` that stores Iris Dataset, connect to SQLite DB via `helper_utils` function - `create_sqlite_conn()`, implement the `read_from_sql_db` function that returns a tuple of 3 `pd.DataFrame` read from SQLite DB Connection to a DB file (take into consideration that SQLite has no native support for specification of Table name as a string to `sql` argument - other DB connection drivers may have this implemented), but with the following conditions:

1. `df_from_sql_db_1`: A simple `pd.DataFrame` with entire dataset as it is in the SQLite DB,
2. `df_from_sql_db_2`: A `pd.DataFrame` with last 10 rows and index column set to `id` and last `2` columns and `id` column,
3. `df_from_sql_db_3`: A `pd.DataFrame` with first 15 rows, index column set to `id` and where `species` feature/column is either `setosa` or `versicolor` and `sepalLength` feature/column is between `4.7` and `5.0`.

<details>
  <summary><b><font color="green">Additional Code Hints (Click to expand if you are stuck)</font></b></summary>
  
  **For `df_from_sql_db_1`:** Use only the defined SQL Query and Connection as the only argument in the `pandas` function that reads from Excel file.

  **For `df_from_sql_db_2`:** Take into consideration that it is required to specify the column name for index column and not the index number. Also, use `pd.DataFrame` methods for selecting a subset of data samples from the end of the data.

  **For `df_from_sql_db_3`:** Similarily with `df_from_sql_db_2` hint. Also, use parametrized SQL query with `params` specified with actual values (either using a map-like structure or tuple with values only). Research how SQL queries are formed with parameters (look also for SQLite specific syntax).

  <details>
  <summary><b><font color="green">Final Code Hints (Click to expand if you are completely stuck)</font></b></summary>
    
  **For `df_from_sql_db_1`:** Use the following code:
  ```py
  df_from_sql_db_1: pd.DataFrame = pd.read_sql(sql=f"SELECT * FROM {table_name}", con=sqlite_conn)
  ```

  **For `df_from_sql_db_2`:** Use the following code:
  ```py
  all_cols = pd.read_sql(sql=f"PRAGMA table_info({table_name})", con=sqlite_conn)["name"].tolist()
  last_two_cols = all_cols[-2:]
  df_from_sql_db_2: pd.DataFrame = pd.read_sql(sql=f"SELECT id, {", ".join(last_two_cols)} FROM {table_name}", con=sqlite_conn, index_col="id", columns=last_two_cols).tail(n=10)
  ```

  **For `df_from_sql_db_3`:** Use the following code:
  ```py
  df_from_sql_db_3 = pd.read_sql(
    sql=f"""
        SELECT * FROM {table_name}
        WHERE species IN (?, ?)
        AND sepalLength BETWEEN ? AND ?
    """,
    con=sqlite_conn,
    index_col="id",
    params=('setosa', 'versicolor', 4.7, 5.0)
  )
  ```

  </details>

</details>

In [80]:
# GRADED FUNCTION: read_from_sql_db
def read_from_sql_db() -> tuple[pd.DataFrame]:
    """Creates and returns 3 different pd.DataFrame using various arguments combinations from `pd.read_sql()` function.

    Using predefined path to SQLite DB file `path_to_sqlite_db_file` that stores Iris Dataset, connect to SQLite DB via 
    `helper_utils` function - `create_sqlite_conn()`, implement the `read_from_sql_db` function that returns a tuple of 
    3 `pd.DataFrame` read from SQLite DB Connection to a DB file (take into consideration that SQLite has no native 
    support for specification of Table name as a string to `sql` argument - other DB connection drivers may have this 
    implemented).
    
    Returns:
        tuple[pd.DataFrame]: A tuple containing 3 pd.DataFrame objects:
            - df_from_sql_db_1: A simple pd.DataFrame with entire dataset as it is in the SQLite DB.
            - df_from_sql_db_2: A pd.DataFrame with last 10 rows and index column set to id and last 2 columns and id column. 
            - df_from_sql_db_3: A pd.DataFrame with all rows, index column set to id and where species 
                                feature/column is either setosa or versicolor and sepalLength feature/column 
                                is between 4.7 and 5.0.
    """
    
    # Defined path to SQLite DB file.
    path_to_sqlite_db_file = helper_utils.get_path_to_dataset_by_type(dataset_type="sql_db")
    sqlite_conn = helper_utils.create_sqlite_conn(db_path=path_to_sqlite_db_file)
    table_name = "IRIS_DATASET_TABLE"
    
    ### START CODE HERE ###
    # You may, and we encourage you to, add intermediary objects if required, but keep all your custom code inside this section.

    # `pd.DataFrame` with entire dataset as it is in the SQLite DB.
    df_from_sql_db_1: pd.DataFrame = pd.read_sql(sql=f"SELECT * FROM {table_name}", con=sqlite_conn)
    
    # `pd.DataFrame` with last `10` rows and index column set to `id` and last `2` columns and `s` column.
    all_cols = pd.read_sql(sql=f"PRAGMA table_info({table_name})", con=sqlite_conn)["name"].tolist()
    last_two_cols = all_cols[-2:]
    
    df_from_sql_db_2: pd.DataFrame = pd.read_sql(sql=f"SELECT id, {", ".join(last_two_cols)} FROM {table_name}", con=sqlite_conn, index_col="id", columns=last_two_cols).tail(n=10)
    
    # `pd.DataFrame` with first `15` rows, index column set to `id` and where `species` 
    #   feature/column is either `setosa` or `versicolor` and `sepalLength` feature/column 
    #   is between `4.7` and `5.0`.
    df_from_sql_db_3: pd.DataFrame = pd.read_sql(
        sql=f"""
            SELECT * FROM {table_name}
            WHERE species IN (?, ?)
            AND sepalLength BETWEEN ? AND ?
        """,
        con=sqlite_conn,
        index_col="id",
        params=('setosa', 'versicolor', 4.7, 5.0)
    )
    
    ### END CODE HERE ###
    
    helper_utils.close_sqlite_conn(conn=connection_sqlite)
    
    return df_from_sql_db_1, df_from_sql_db_2, df_from_sql_db_3

In [81]:
df_from_sql_db_1, df_from_sql_db_2, df_from_sql_db_3 = read_from_sql_db()

In [82]:
# DATAFRAME_FROM_SQL_1
df_from_sql_db_1

      id  sepalLength  sepalWidth  petalLength  petalWidth    species
0      1          5.1         3.5          1.4         0.2     setosa
1      2          4.9         3.0          1.4         0.2     setosa
2      3          4.7         3.2          1.3         0.2     setosa
3      4          4.6         3.1          1.5         0.2     setosa
4      5          5.0         3.6          1.4         0.2     setosa
..   ...          ...         ...          ...         ...        ...
145  146          6.7         3.0          5.2         2.3  virginica
146  147          6.3         2.5          5.0         1.9  virginica
147  148          6.5         3.0          5.2         2.0  virginica
148  149          6.2         3.4          5.4         2.3  virginica
149  150          5.9         3.0          5.1         1.8  virginica

[150 rows x 6 columns]

In [83]:
# DATAFRAME_FROM_SQL_2
df_from_sql_db_2

     petalWidth    species
id
141         2.4  virginica
142         2.3  virginica
143         1.9  virginica
144         2.3  virginica
145         2.5  virginica
146         2.3  virginica
147         1.9  virginica
148         2.0  virginica
149         2.3  virginica
150         1.8  virginica

In [84]:
# DATAFRAME_FROM_SQL_3
df_from_sql_db_3

    sepalLength  sepalWidth  petalLength  petalWidth     species
id
2           4.9         3.0          1.4         0.2      setosa
3           4.7         3.2          1.3         0.2      setosa
5           5.0         3.6          1.4         0.2      setosa
8           5.0         3.4          1.5         0.2      setosa
10          4.9         3.1          1.5         0.1      setosa
12          4.8         3.4          1.6         0.2      setosa
13          4.8         3.0          1.4         0.1      setosa
25          4.8         3.4          1.9         0.2      setosa
26          5.0         3.0          1.6         0.2      setosa
27          5.0         3.4          1.6         0.4      setosa
30          4.7         3.2          1.6         0.2      setosa
31          4.8         3.1          1.6         0.2      setosa
35          4.9         3.1          1.5         0.2      setosa
36          5.0         3.2          1.2         0.2      setosa
38          4.9         3.6          1.4         0.1      setosa
41          5.0         3.5          1.3         0.3      setosa
44          5.0         3.5          1.6         0.6      setosa
46          4.8         3.0          1.4         0.3      setosa
50          5.0         3.3          1.4         0.2      setosa
58          4.9         2.4          3.3         1.0  versicolor
61          5.0         2.0          3.5         1.0  versicolor
94          5.0         2.3          3.3         1.0  versicolor

In [85]:
# Test your implementation
unittests.exercise_6(read_from_sql_db)

 All tests passed!

## Conclusion

Congratulations! You have successfully completed the Multi-Format Data Loading assignment.

In this assignment, you explored how real-world datasets can exist in multiple formats and how to efficiently load and standardize them for analysis using `pandas`. You moved beyond working with a single file type and learned to handle structured and semi-structured data originating from different sources.

You practiced reading tabular datasets from CSV and Excel files, importing flexible JSON data with varying schemas, querying relational databases through SQL connections, and fetching external data from web APIs. You also learned how to apply the appropriate parameters and techniques for each format to ensure that the data is correctly interpreted and converted into consistent `DataFrame` structures.

With these core techniques—file readers, database queries, JSON parsing, and API integration—you now have a strong foundation for building robust data ingestion pipelines that prepare datasets from multiple sources for further processing, analysis, and modeling.